const translations = {
    "en": {
        "app_name": "ToWebP", "files": "files", "total_saved_header": "Total Saved: ", "download_zip": "Download ZIP", "clear": "Clear", "format": "Format", "quality": "Quality", "hero_title": "The best & fastest way to convert your images to WebP", "hero_subtitle": "Client side, no upload needed - 100% privacy and 100% saved bandwidth", "drag_drop_images": "Drag & Drop images here", "click_browse_p": "or click to browse", "drag_drop": "Drag & Drop", "click_browse": "or click to browse", "feature_1_title": "🚀 Fast & Secure", "feature_1_desc": "All conversions happen locally on your device. Your images never leave your computer, ensuring 100% privacy.", "feature_2_title": "📉 Smart Compression", "feature_2_desc": "Reduce file size by up to 80% without visible quality loss. WebP is the modern standard for lighter websites.", "feature_3_title": "⚡ Batch Process", "feature_3_desc": "Convert hundreds of images in seconds using multi-core processing. Drag, drop, and done.", "why_use_title": "Why use ToWebP?", "why_use_p1": "ToWebP is a privacy-first image converter that runs entirely in your browser. Unlike other online converters, we do not upload your images to any server. This means your photos, designs, and documents remain 100% confidential and never leave your device.", "why_use_p2": "No Cookies, No Tracking. We believe in a clean and fast web. This site does not use persistent cookies or trackers, so you won't be pestered by consent banners. Just drag, drop, and convert with zero traces left behind.", "download": "DOWNLOAD",
        "processing": "Processing...", "parsing_files": "Parsing files...", "waiting": "Waiting...", "total_saved_prefix": "Total Saved:", "saved": "saved", "starting": "Starting...", "select_language": "Select Language"
    },
    "ro": {
        "app_name": "ToWebP", "files": "fișiere", "total_saved_header": "Total Salvat: ", "download_zip": "Descarcă ZIP", "clear": "Șterge", "format": "Format", "quality": "Calitate", "hero_title": "Cea mai bună și rapidă cale de a converti imaginile în WebP", "hero_subtitle": "Rulează în browser, fără încărcare pe server - 100% confidențialitate și bandă economisită", "drag_drop_images": "Trage și plasează imaginile aici", "click_browse_p": "sau click pentru a selecta", "drag_drop": "Trage și plasează", "click_browse": "sau click pentru a selecta", "feature_1_title": "🚀 Rapid și Sigur", "feature_1_desc": "Toate conversiile au loc local pe dispozitivul tău. Imaginile nu părăsesc niciodată computerul tău, asigurând confidențialitate 100%.", "feature_2_title": "📉 Compresie Inteligentă", "feature_2_desc": "Redu dimensiunea fișierelor cu până la 80% fără pierderi vizibile de calitate. WebP este standardul modern pentru site-uri rapide.", "feature_3_title": "⚡ Procesare în Masă", "feature_3_desc": "Convertește sute de imagini în câteva secunde folosind procesare multi-core. Trage, plasează și gata.", "why_use_title": "De ce să folosești ToWebP?", "why_use_p1": "ToWebP este un convertor de imagini centrat pe confidențialitate care rulează în întregime în browserul tău. Spre deosebire de alte convertoare online, nu încărcăm imaginile tale pe niciun server. Acest lucru înseamnă că fotografiile, design-urile și documentele tale rămân 100% confidențiale.", "why_use_p2": "Fără module cookie, fără urmărire. Credem într-un web curat și rapid. Acest site nu folosește module cookie persistente sau trackere, deci nu vei fi deranjat de bannere de consimțământ.", "download": "DESCARCĂ",
        "processing": "Procesare...", "parsing_files": "Citire fișiere...", "waiting": "În așteptare...", "total_saved_prefix": "Total Salvat:", "saved": "salvat", "starting": "Se pornește...", "select_language": "Selectează Limba"
    },
    "fr": {
        "app_name": "ToWebP", "files": "fichiers", "total_saved_header": "Économie Totale : ", "download_zip": "Télécharger ZIP", "clear": "Effacer", "format": "Format", "quality": "Qualité", "hero_title": "Le moyen le plus simple et rapide de convertir vos images en WebP", "hero_subtitle": "Côté client, sans téléchargement - 100% confidentialité et 100% bande passante économisée", "drag_drop_images": "Glissez-déposez vos images ici", "click_browse_p": "ou cliquez pour parcourir", "drag_drop": "Glisser-déposer", "click_browse": "ou cliquez pour parcourir", "feature_1_title": "🚀 Rapide & Sécurisé", "feature_1_desc": "Toutes les conversions se font localement sur votre appareil. Vos images ne quittent jamais votre ordinateur.", "feature_2_title": "📉 Compression Intelligente", "feature_2_desc": "Réduisez la taille des fichiers jusqu'à 80% sans perte de qualité visible.", "feature_3_title": "⚡ Traitement par Lot", "feature_3_desc": "Convertissez des centaines d'images en quelques secondes.", "why_use_title": "Pourquoi utiliser ToWebP ?", "why_use_p1": "ToWebP est un convertisseur privé qui s'exécute entièrement dans votre navigateur.", "why_use_p2": "Pas de cookies, pas de suivi. Nous croyons en un web propre et rapide.", "download": "TÉLÉCHARGER",
        "processing": "Traitement...", "parsing_files": "Analyse des fichiers...", "waiting": "En attente...", "total_saved_prefix": "Économie Totale:", "saved": "sauvé", "starting": "Démarrage...", "select_language": "Choisir la Langue"
    },
    "de": {
        "app_name": "ToWebP", "files": "Dateien", "total_saved_header": "Insgesamt gespart: ", "download_zip": "ZIP herunterladen", "clear": "Löschen", "format": "Format", "quality": "Qualität", "hero_title": "Der beste Weg, Bilder in WebP zu konvertieren", "hero_subtitle": "Lokal im Browser, kein Upload - 100% Privatsphäre", "drag_drop_images": "Bilder hierher ziehen", "click_browse_p": "oder klicken zum Durchsuchen", "drag_drop": "Drag & Drop", "click_browse": "oder klicken", "feature_1_title": "🚀 Schnell & Sicher", "feature_1_desc": "Alle Konvertierungen finden lokal auf Ihrem Gerät statt.", "feature_2_title": "📉 Intelligente Kompression", "feature_2_desc": "Bis zu 80% kleinere Dateien ohne Qualitätsverlust.", "feature_3_title": "⚡ Stapelverarbeitung", "feature_3_desc": "Hunderte Bilder in Sekunden konvertieren.", "why_use_title": "Warum ToWebP nutzen?", "why_use_p1": "ToWebP ist ein privater Konverter, der komplett im Browser läuft.", "why_use_p2": "Keine Cookies, kein Tracking.", "download": "DOWNLOAD",
        "processing": "Verarbeitung...", "parsing_files": "Dateien werden gelesen...", "waiting": "Warten...", "total_saved_prefix": "Insgesamt gespart:", "saved": "gespart", "starting": "Startet..."
    },
    "es": {
        "app_name": "ToWebP", "files": "archivos", "total_saved_header": "Ahorro total: ", "download_zip": "Descargar ZIP", "clear": "Limpiar", "format": "Formato", "quality": "Calidad", "hero_title": "La mejor forma de convertir tus imágenes a WebP", "hero_subtitle": "Local en el navegador, sin subidas - 100% privacidad", "drag_drop_images": "Arrastra las imágenes aquí", "click_browse_p": "o haz clic para buscar", "drag_drop": "Arrastrar y soltar", "click_browse": "o haz clic", "feature_1_title": "🚀 Rápido y Seguro", "feature_1_desc": "Todas las conversiones ocurren localmente en tu dispositivo.", "feature_2_title": "📉 Compresión Inteligente", "feature_2_desc": "Reduce el tamaño hasta un 80% sin pérdida visible.", "feature_3_title": "⚡ Procesamiento por Lote", "feature_3_desc": "Convierte cientos de imágenes en segundos.", "why_use_title": "¿Por qué usar ToWebP?", "why_use_p1": "ToWebP es un convertidor privado que funciona en tu navegador.", "why_use_p2": "Sin cookies ni rastreo.", "download": "DESCARGAR",
        "processing": "Procesando...", "parsing_files": "Analizando archivos...", "waiting": "Esperando...", "total_saved_prefix": "Ahorro Total:", "saved": "ahorrado", "starting": "Iniciando..."
    },
    "it": {
        "app_name": "ToWebP", "files": "file", "total_saved_header": "Risparmio totale: ", "download_zip": "Scarica ZIP", "clear": "Pulisci", "format": "Formato", "quality": "Qualità", "hero_title": "Il modo migliore per convertire le immagini in WebP", "hero_subtitle": "Locale nel browser, nessun upload - 100% privacy", "drag_drop_images": "Trascina le immagini qui", "click_browse_p": "o clicca per sfogliare", "drag_drop": "Trascina e rilascia", "click_browse": "o clicca", "feature_1_title": "🚀 Veloce & Sicuro", "feature_1_desc": "Tutte le conversioni avvengono localmente sul tuo dispositivo.", "feature_2_title": "📉 Compressione Intelligente", "feature_2_desc": "Riduci le dimensioni fino all'80% senza perdita visibile.", "feature_3_title": "⚡ Elaborazione a Lotti", "feature_3_desc": "Converti centinaia di immagini in pochi secondi.", "why_use_title": "Perché usare ToWebP?", "why_use_p1": "ToWebP è un convertitore privato che gira nel tuo browser.", "why_use_p2": "Niente cookie, niente tracciamento.", "download": "SCARICA",
        "processing": "Elaborazione...", "parsing_files": "Analisi file...", "waiting": "In attesa...", "total_saved_prefix": "Risparmio Totale:", "saved": "risparmiato", "starting": "Avvio..."
    },
    "pt": {
        "app_name": "ToWebP", "files": "arquivos", "total_saved_header": "Total economizado: ", "download_zip": "Baixar ZIP", "clear": "Limpar", "format": "Formato", "quality": "Qualidade", "hero_title": "A melhor forma de transformar suas imagens em WebP", "hero_subtitle": "No navegador, sem upload - 100% de privacidade", "drag_drop_images": "Arraste as imagens para cá", "click_browse_p": "ou clique para navegar", "drag_drop": "Arrastar e soltar", "click_browse": "ou clique", "feature_1_title": "🚀 Rápido e Seguro", "feature_1_desc": "Todas as conversões ocorrem localmente no seu dispositivo.", "feature_2_title": "📉 Compressão Inteligente", "feature_2_desc": "Reduza o tamanho em até 80% sem perda visível.", "feature_3_title": "⚡ Processamento em Lote", "feature_3_desc": "Converta centenas de imagens em segundos.", "why_use_title": "Por que usar ToWebP?", "why_use_p1": "ToWebP é um conversor privado que roda no seu navegador.", "why_use_p2": "Sem cookies, sem rastreamento.", "download": "BAIXAR",
        "processing": "Processando...", "parsing_files": "Analisando arquivos...", "waiting": "Aguardando...", "total_saved_prefix": "Total Economizado:", "saved": "economizado", "starting": "Iniciando..."
    },
    "nl": {
        "app_name": "ToWebP", "files": "bestanden", "total_saved_header": "Totaal bespaard: ", "download_zip": "Download ZIP", "clear": "Wissen", "format": "Formaat", "quality": "Kwaliteit", "hero_title": "De beste manier om afbeeldingen naar WebP te converteren", "hero_subtitle": "Lokaal in de browser, geen upload - 100% privacy", "drag_drop_images": "Sleep afbeeldingen hierheen", "click_browse_p": "of klik om te bladeren", "drag_drop": "Slepen en neerzetten", "click_browse": "of klik", "feature_1_title": "🚀 Snel & Veilig", "feature_1_desc": "Alle conversies vinden lokaal plaats op uw apparaat.", "feature_2_title": "📉 Slimme Compressie", "feature_2_desc": "Verklein bestanden tot 80% zonder zichtbaar kwaliteitsverlies.", "feature_3_title": "⚡ Batchverwerking", "feature_3_desc": "Converteer honderden afbeeldingen in seconden.", "why_use_title": "Waarom ToWebP gebruiken?", "why_use_p1": "ToWebP is een privacyvriendelijke converter die in uw browser werkt.", "why_use_p2": "Geen cookies, geen tracking.", "download": "DOWNLOADEN",
        "processing": "Verwerken...", "parsing_files": "Bestanden analyseren...", "waiting": "Wachten...", "total_saved_prefix": "Totaal Bespaard:", "saved": "bespaard", "starting": "Starten..."
    },
    "el": {
        "app_name": "ToWebP", "files": "αρχεία", "total_saved_header": "Συνολική εξοικονόμηση: ", "download_zip": "Λήψη ZIP", "clear": "Καθαρισμός", "format": "Μορφή", "quality": "Ποιότητα", "hero_title": "Ο καλύτερος τρόπος για να μετατρέψετε τις εικόνες σας σε WebP", "hero_subtitle": "Τοπικά στο πρόγραμμα περιήγησης, χωρίς μεταφόρτωση - 100% ιδιωτικότητα", "drag_drop_images": "Σύρετε τις εικόνες εδώ", "click_browse_p": "ή κάντε κλικ για περιήγηση", "drag_drop": "Σύρετε και αφήστε", "click_browse": "ή κάντε κλικ", "feature_1_title": "🚀 Γρήγορο & Ασφαλές", "feature_1_desc": "Όλες οι μετατροπές γίνονται τοπικά στη συσκευή σας.", "feature_2_title": "📉 Έξυπνη συμπίεση", "feature_2_desc": "Μειώστε το μέγεθος έως και 80% χωρίς ορατή απώλεια ποιότητας.", "feature_3_title": "⚡ Μαζική επεξεργασία", "feature_3_desc": "Μετατρέψτε εκατοντάδες εικόνες σε δευτερόλεπτα.", "why_use_title": "Γιατί να χρησιμοποιήσετε το ToWebP;", "why_use_p1": "Το ToWebP είναι ένας μετατροπέας με επίκεντρο την ιδιωτικότητα που τρέχει στο πρόγραμμα περιήγησης.", "why_use_p2": "Χωρίς cookies, χωρίς παρακολούθηση.", "download": "ΛΗΨΗ",
        "processing": "Επεξεργασία...", "parsing_files": "Ανάλυση αρχείων...", "waiting": "Αναμονή...", "total_saved_prefix": "Συνολική Εξοικονόμηση:", "saved": "εξοικονομήθηκαν", "starting": "Έναρξη..."
    },
    "hu": {
        "app_name": "ToWebP", "files": "fájl", "total_saved_header": "Összesen megtakarítva: ", "download_zip": "ZIP letöltése", "clear": "Törlés", "format": "Formátum", "quality": "Minőség", "hero_title": "A legjobb és leggyorsabb módja a képek WebP-be alakításának", "hero_subtitle": "Helyben a böngészőben, nincs feltöltés - 100% adatvédelem", "drag_drop_images": "Húzza ide a képeket", "click_browse_p": "vagy kattintson a tallózáshoz", "drag_drop": "Húzd és ejtsd", "click_browse": "vagy kattints", "feature_1_title": "🚀 Gyors és biztonságos", "feature_1_desc": "Minden átalakítás helyben történik az eszközén.", "feature_2_title": "📉 Intelligens tömörítés", "feature_2_desc": "Csökkentse a fájlméretet akár 80%-kal látható minőségromlás nélkül.", "feature_3_title": "⚡ Kötegelt feldolgozás", "feature_3_desc": "Konvertáljon több száz képet másodpercek alatt.", "why_use_title": "Miért használja a ToWebP-t?", "why_use_p1": "A ToWebP egy adatvédelem-központú konvertáló, amely a böngészőjében fut.", "why_use_p2": "Nincsenek sütik, nincs nyomon követés.", "download": "LETÖLTÉS",
        "processing": "Feldolgozás...", "parsing_files": "Fájlok elemzése...", "waiting": "Várakozás...", "total_saved_prefix": "Összesen Megtakarítva:", "saved": "megtakarítva", "starting": "Indítás..."
    },
    "pl": {
        "app_name": "ToWebP", "files": "plików", "total_saved_header": "Łącznie zaoszczędzono: ", "download_zip": "Pobierz ZIP", "clear": "Wyczyść", "format": "Format", "quality": "Jakość", "hero_title": "Najlepszy i najszybszy sposób na konwersję obrazów do WebP", "hero_subtitle": "Lokalnie w przeglądarce, bez przesyłania - 100% prywatności", "drag_drop_images": "Przeciągnij obrazy tutaj", "click_browse_p": "lub kliknij, aby przeglądać", "drag_drop": "Przeciągnij i upuść", "click_browse": "lub kliknij", "feature_1_title": "🚀 Szybko i bezpiecznie", "feature_1_desc": "Wszystkie konwersje odbywają się lokalnie na Twoim urządzeniu.", "feature_2_title": "📉 Inteligentna kompresja", "feature_2_desc": "Zmniejsz rozmiar pliku nawet o 80% bez widocznej utraty jakości.", "feature_3_title": "⚡ Przetwarzanie wsadowe", "feature_3_desc": "Konwertuj setki obrazów w kilka sekund.", "why_use_title": "Dlaczego warto korzystać z ToWebP?", "why_use_p1": "ToWebP to konwerter chroniący prywatność, który działa w całości w Twojej przeglądarce.", "why_use_p2": "Bez ciasteczek, bez śledzenia.", "download": "POBIERZ",
        "processing": "Przetwarzanie...", "parsing_files": "Analizowanie plików...", "waiting": "Oczekiwanie...", "total_saved_prefix": "Łącznie Zaoszczędzono:", "saved": "zaoszczędzono", "starting": "Uruchamianie..."
    },
    "ar": {
        "app_name": "ToWebP", "files": "ملفات", "total_saved_header": "إجمالي التوفير: ", "download_zip": "تحميل ZIP", "clear": "مسح", "format": "تنسيق", "quality": "جودة", "hero_title": "أفضل وأسرع طريقة لتحويل صورκ إلى WebP", "hero_subtitle": "على جهازك، بدون رفع - خصوصية 100٪ وتوفير 100٪ في النطاق الترددي", "drag_drop_images": "اسحب وأفلت الصور هنا", "click_browse_p": "أو انقر للتصفح", "drag_drop": "سحب وإفلات", "click_browse": "أو انقر للتصفح", "feature_1_title": "🚀 سريع وآمن", "feature_1_desc": "تتم جميع التحويلات محليًا على جهازك.", "feature_2_title": "📉 ضغط ذكي", "feature_2_desc": "تقليل حجم الملف بنسبة تصل إلى 80٪ بدون فقدان جودة ملحوظ.", "feature_3_title": "⚡ معالجة مجمعة", "feature_3_desc": "تحويل مئات الصور في ثوانٍ.", "why_use_title": "لماذا تستخدم ToWebP؟", "why_use_p1": "ToWebP هو محول صور يهتم بالخصوصية يعمل بالكامل σε متصفحك.", "why_use_p2": "بدون ملفات تعريف ارتباط، بدون تتبع.", "download": "تحميل",
        "processing": "جاري المعالجة...", "parsing_files": "جاري تحليل الملفات...", "waiting": "في الانتظار...", "total_saved_prefix": "إجمالي التوفير:", "saved": "تم توفيره", "starting": "جاري البدء..."
    },
    "bg": {
        "app_name": "ToWebP", "files": "файла", "total_saved_header": "Общо спестени: ", "download_zip": "Изтегли ZIP", "clear": "Изчисти", "format": "Формат", "quality": "Качество", "hero_title": "Най-добрият и бърз начин за конвертиране на изображения в WebP", "hero_subtitle": "Локално в браузъρα, без качване - 100% поверителност", "drag_drop_images": "Плъзнете изображенията тук", "click_browse_p": "или кликнете за преглед", "drag_drop": "Πлъзгане и пускаνε", "click_browse": "или кликнете", "feature_1_title": "🚀 Бързо и сигурнο", "feature_1_desc": "Всички конвертирания се случват локално на вашеτο устройство.", "feature_2_title": "📉 Интелигентна компресия", "feature_2_desc": "Намалете размера с до 80% без видима загуба на качество.", "feature_3_title": "⚡ Групова обработка", "feature_3_desc": "Конвертирайте стотици изображения за секунди.", "why_use_title": "Защо да използвате ToWebP?", "why_use_p1": "ToWebP е конвертор, фокусиран върху повеριтелността, който рабоτι изцяλο във вашия браузър.", "why_use_p2": "Без биσквитки, без проследяване.", "download": "ИЗТЕΓЛИ",
        "processing": "Обрабоτκα...", "parsing_files": "Анализиране на файлове...", "waiting": "Изчаκване...", "total_saved_prefix": "Общо Сπεстени:", "saved": "сπεстени", "starting": "Стартиране..."
    },
    "ja": {
        "app_name": "ToWebP", "files": "ファイル", "total_saved_header": "合計節約量: ", "download_zip": "ZIPをダウンロード", "clear": "クリア", "format": "形式", "quality": "画質", "hero_title": "画像をWebPに変換する最適で最速な方法", "hero_subtitle": "ブラウザ内で完結、アップロード不要 - 100%のプライバシー保護", "drag_drop_images": "ここに画像をドラッグ＆ドロップ", "click_browse_p": "またはクリックして選択", "drag_drop": "ドラッグ＆ドロップ", "click_browse": "またはクリック", "feature_1_title": "🚀 高速で安全", "feature_1_desc": "すべての変換はデバイス上でローカルに行われます。", "feature_2_title": "📉 スマート圧縮", "feature_2_desc": "画質を維持したまま、ファイルサイズを最大80%削減します。", "feature_3_title": "⚡ 一括処理", "feature_3_desc": "数百枚の画像を数秒で変換できます。", "why_use_title": "なぜToWebPを使うのか？", "why_use_p1": "ToWebPは、ブラウザだけで動作するプライバシー重視の画像コンバーターです。", "why_use_p2": "Cookieなし、追跡なし。", "download": "ダウンロード",
        "processing": "処理中...", "parsing_files": "ファイルを解析中...", "waiting": "待機中...", "total_saved_prefix": "合計節約量:", "saved": "節約済み", "starting": "開始中..."
    },
    "zh": {
        "app_name": "ToWebP", "files": "个文件", "total_saved_header": "总共节省：", "download_zip": "下载 ZIP", "clear": "清除", "format": "格式", "quality": "质量", "hero_title": "将图片转换为 WebP 的最佳且最快的方式", "hero_subtitle": "客户端处理，无需上传 - 100% 隐私保护", "drag_drop_images": "将图片拖放到此处", "click_browse_p": "或点击浏览", "drag_drop": "拖放", "click_browse": "或点击", "feature_1_title": "🚀 快速且安全", "feature_1_desc": "所有转换均在您的设备上本地运行。", "feature_2_title": "📉 智能压缩", "feature_2_desc": "在不损失可见画质的情况下，可减少高达 80% 的文件大小。", "feature_3_title": "⚡ 批量处理", "feature_3_desc": "数秒内转换数百张图片。", "why_use_title": "为什么选择 ToWebP？", "why_use_p1": "ToWebP 是一款完全在浏览器中运行的隐私优先图片转换器。", "why_use_p2": "无 Cookie，无追踪。", "download": "下载",
        "processing": "处理中...", "parsing_files": "解析文件...", "waiting": "等待中...", "total_saved_prefix": "总共节省:", "saved": "已节省", "starting": "开始..."
    },
    "cs": {
        "app_name": "ToWebP", "files": "souborů", "total_saved_header": "Celkem ušetřeno: ", "download_zip": "Stáhnout ZIP", "clear": "Vymazat", "format": "Formát", "quality": "Kvalita", "hero_title": "Nejlepší a nejrychlejší způsob převodu obrázků do WebP", "hero_subtitle": "Lokálně v prohlížeči, žádné nahrávání - 100% soukromí", "drag_drop_images": "Přetáhněte sem obrázky", "click_browse_p": "nebo klikněte pro procházení", "drag_drop": "Přetáhnout", "click_browse": "nebo klikněte", "feature_1_title": "🚀 Rychlé a bezpečné", "feature_1_desc": "Všechny převody probíhají lokálně na vašem zařízení.", "feature_2_title": "📉 Chytrá komprese", "feature_2_desc": "Zmenšete velikost až o 80 % bez viditelné ztráty kvality.", "feature_3_title": "⚡ Hromadné zpracování", "feature_3_desc": "Převeďte stovky obrázků během sekund.", "why_use_title": "Proč používat ToWebP?", "why_use_p1": "ToWebP je konvertor zaměřený na soukromí běžící v prohlížeči.", "why_use_p2": "Žádné cookies, žádné sledování.", "download": "STÁHNOUT",
        "processing": "Zpracování...", "parsing_files": "Načítání...", "waiting": "Čekání...", "total_saved_prefix": "Celkem Ušetřeno:", "saved": "ušetřeno", "starting": "Spouštění..."
    },
    "da": {
        "app_name": "ToWebP", "files": "filer", "total_saved_header": "Samlet sparet: ", "download_zip": "Hent ZIP", "clear": "Ryd", "format": "Format", "quality": "Kvalitet", "hero_title": "Den bedste og hurtigste måde at konvertere billeder til WebP", "hero_subtitle": "Lokalt i browseren - 100% privatliv", "drag_drop_images": "Træk billeder herhen", "click_browse_p": "eller klik for at gennemse", "drag_drop": "Træk og slip", "click_browse": "eller klik", "feature_1_title": "🚀 Hurtig & Sikker", "feature_1_desc": "Alle konverteringer sker lokalt på din enhed.", "feature_2_title": "📉 Smart Komprimering", "feature_2_desc": "Reducer filstørrelsen op til 80% uden synligt kvalitetstab.", "feature_3_title": "⚡ Batch-behandling", "feature_3_desc": "Konverter hundredvis af billeder på sekunder.", "why_use_title": "Hvorfor bruge ToWebP?", "why_use_p1": "ToWebP kører udelukkende i din browser.", "why_use_p2": "Ingen cookies, ingen tracking.", "download": "HENT",
        "processing": "Behandler...", "parsing_files": "Analyserer...", "waiting": "Venter...", "total_saved_prefix": "Samlet Sparet:", "saved": "sparet", "starting": "Starter..."
    },
    "sv": {
        "app_name": "ToWebP", "files": "filer", "total_saved_header": "Totalt sparat: ", "download_zip": "Ladda ner ZIP", "clear": "Rensa", "format": "Format", "quality": "Kvalitet", "hero_title": "Det bästa och snabbaste sättet att konvertera bilder till WebP", "hero_subtitle": "Lokalt i webbläsaren - 100% integritet", "drag_drop_images": "Dra bilder hit", "click_browse_p": "eller klicka för att bläddra", "drag_drop": "Dra och släpp", "click_browse": "eller klicka", "feature_1_title": "🚀 Snabb & Säker", "feature_1_desc": "Alla konverteringar sker lokalt på din enhet.", "feature_2_title": "📉 Smart Komprimering", "feature_2_desc": "Minska filstorleken upp till 80% utan synlig kvalitetsförlust.", "feature_3_title": "⚡ Batchhantering", "feature_3_desc": "Konvertera hundratals bilder på sekunder.", "why_use_title": "Varför använda ToWebP?", "why_use_p1": "ToWebP körs helt i din webbläsare.", "why_use_p2": "Inga cookies, ingen spårning.", "download": "LADDA NER",
        "processing": "Bearbetar...", "parsing_files": "Tolkar...", "waiting": "Väntar...", "total_saved_prefix": "Totalt Sparat:", "saved": "sparat", "starting": "Startar..."
    },
    "fi": {
        "app_name": "ToWebP", "files": "tiedostoa", "total_saved_header": "Säästetty yhteensä: ", "download_zip": "Lataa ZIP", "clear": "Tyhjennä", "format": "Muoto", "quality": "Laatu", "hero_title": "Paras ja nopein tapa muuntaa kuvat WebP-muotoon", "hero_subtitle": "Paikallisesti selaimessa - 100% yksityisyys", "drag_drop_images": "Vedä kuvat tähän", "click_browse_p": "tai napsauta selataksesi", "drag_drop": "Vedä ja pudota", "click_browse": "tai napsauta", "feature_1_title": "🚀 Nopea & Turvallinen", "feature_1_desc": "Kaikki muunnokset tapahtuvat laitteellasi.", "feature_2_title": "📉 Älykäs pakkaus", "feature_2_desc": "Pienennä tiedostokokoa jopa 80% ilman näkyvää laatuhäviötä.", "feature_3_title": "⚡ Joukkokäsittely", "feature_3_desc": "Muunna satoja kuvia sekunneissa.", "why_use_title": "Miksi käyttää ToWebP:tä?", "why_use_p1": "ToWebP toimii kokonaan selaimessasi.", "why_use_p2": "Ei evästeitä, ei seurantaa.", "download": "LATAA",
        "processing": "Käsitellään...", "parsing_files": "Luetaan...", "waiting": "Odotetaan...", "total_saved_prefix": "Säästetty Yhteensä:", "saved": "säästetty", "starting": "Käynnistetään..."
    },
    "ru": {
        "app_name": "ToWebP", "files": "файлов", "total_saved_header": "Всего сохранено: ", "download_zip": "Скачать ZIP", "clear": "Очистить", "format": "Формат", "quality": "Качество", "hero_title": "Лучший и самый быстрый способ конвертации в WebP", "hero_subtitle": "Локально в браузере - 100% конфиденциальность", "drag_drop_images": "Перетащите изображения сюда", "click_browse_p": "или нажмите для выбора", "drag_drop": "Перетащить", "click_browse": "или выбрать", "feature_1_title": "🚀 Быстро и безопасно", "feature_1_desc": "Все преобразования происходят локально на вашем устройстве.", "feature_2_title": "📉 Умное сжатие", "feature_2_desc": "Уменьшите размер до 80% без видимой потери качества.", "feature_3_title": "⚡ Пакетная обработка", "feature_3_desc": "Конвертируйте сотни изображений за секунды.", "why_use_title": "Почему ToWebP?", "why_use_p1": "ToWebP работает полностью в вашем браузере.", "why_use_p2": "Без куки, без трекеров.", "download": "СКАЧАТЬ",
        "processing": "Обработка...", "parsing_files": "Анализ...", "waiting": "Ожидание...", "total_saved_prefix": "Всего сохранено:", "saved": "сохранено", "starting": "Запуск..."
    },
    "tr": {
        "app_name": "ToWebP", "files": "dosya", "total_saved_header": "Toplam Tasarruf: ", "download_zip": "ZIP İndir", "clear": "Temizle", "format": "Format", "quality": "Kalite", "hero_title": "Görselleri WebP'ye dönüştürmenin en iyi yolu", "hero_subtitle": "Tarayıcıda yerel, yükleme yok - %100 gizlilik", "drag_drop_images": "Görselleri buraya sürükleyin", "click_browse_p": "veya göz atmak için tıklayın", "drag_drop": "Sürükle ve Bırak", "click_browse": "veya tıklayın", "feature_1_title": "🚀 Hızlı & Güvenli", "feature_1_desc": "Tüm dönüşümler cihazınızda yerel olarak gerçekleşir.", "feature_2_title": "📉 Akıllı Sıkıştırma", "feature_2_desc": "Görünür kalite kaybı olmadan boyutu %80'e kadar azaltın.", "feature_3_title": "⚡ Toplu İşlem", "feature_3_desc": "Saniyeler içinde yüzlerce görseli dönüştürün.", "why_use_title": "Neden ToWebP?", "why_use_p1": "ToWebP, tamamen tarayıcınızda çalışan gizlilik odaklı bir dönüştürücüdür.", "why_use_p2": "Çerez yok, izleme yok.", "download": "İNDİR",
        "processing": "İşleniyor...", "parsing_files": "Ayrıştırılıyor...", "waiting": "Bekleniyor...", "total_saved_prefix": "Toplam Tasarruf:", "saved": "tasarruf edildi", "starting": "Başlatılıyor..."
    },
    "et": {
        "app_name": "ToWebP", "files": "faili", "total_saved_header": "Kokku säästetud: ", "download_zip": "Laadi alla ZIP", "clear": "Tühjenda", "format": "Vorming", "quality": "Kvaliteet", "hero_title": "Parim ja kiireim viis piltide WebP-ks teisendamiseks", "hero_subtitle": "Kohalik brauseris, ilma üleslaadimiseta - 100% privaatsus", "drag_drop_images": "Lohista pildid siia", "click_browse_p": "või klõpsa sirvimiseks", "drag_drop": "Lohista ja aseta", "click_browse": "või klõpsa", "feature_1_title": "🚀 Kiire ja turvaline", "feature_1_desc": "Kõik teisendused toimuvad kohapeal sinu seadmes.", "feature_2_title": "📉 Nutikas tihendamine", "feature_2_desc": "Vähenda failimahtu kuni 80% ilma nähtava kvaliteedikaota.", "feature_3_title": "⚡ Hulgi töötlemine", "feature_3_desc": "Teisenda sadu pilte sekunditega.", "why_use_title": "Miks kasutada ToWebP-d?", "why_use_p1": "ToWebP on privaatsusele keskendunud konverter, mis töötab täielikult sinu brauseris.", "why_use_p2": "Ei küpsiseid ega jälgimist.", "download": "LAADI ALLA",
        "processing": "Töötlemine...", "parsing_files": "Analüüsimine...", "waiting": "Ootel...", "total_saved_prefix": "Kokku Säästetud:", "saved": "säästetud", "starting": "Käivitamine..."
    },
    "hr": {
        "app_name": "ToWebP", "files": "datoteka", "total_saved_header": "Ukupno ušteđeno: ", "download_zip": "Preuzmi ZIP", "clear": "Očisti", "format": "Format", "quality": "Kvaliteta", "hero_title": "Najbolji i najbrži način za pretvaranje slika u WebP", "hero_subtitle": "Lokalno u pregledniku, bez učitavanja - 100% privatnost", "drag_drop_images": "Povucite slike ovdje", "click_browse_p": "ili kliknite za pregled", "drag_drop": "Povuci i ispusti", "click_browse": "ili klikni", "feature_1_title": "🚀 Brzo i sigurno", "feature_1_desc": "Sve konverzije odvijaju se lokalno na vašem uređaju.", "feature_2_title": "📉 Pametna kompresija", "feature_2_desc": "Smanjite veličinu datoteke do 80% bez vidljivog gubitka kvalitete.", "feature_3_title": "⚡ Grupna obrada", "feature_3_desc": "Pretvorite stotine slika u sekundi.", "why_use_title": "Zašto koristiti ToWebP?", "why_use_p1": "ToWebP je pretvarač usmjeren na privatnost koji radi u potpunosti u vašem pregledniku.", "why_use_p2": "Bez kolačića, bez praćenja.", "download": "PREUZMI",
        "processing": "Obrada...", "parsing_files": "Analiza...", "waiting": "Čekanje...", "total_saved_prefix": "Ukupno Ušteđeno:", "saved": "ušteđeno", "starting": "Pokretanje..."
    },
    "is": {
        "app_name": "ToWebP", "files": "skrár", "total_saved_header": "Heildar sparnaður: ", "download_zip": "Sækja ZIP", "clear": "Hreinsa", "format": "Snið", "quality": "Gæði", "hero_title": "Besta og fljótlegasta leiðin til að breyta myndum í WebP", "hero_subtitle": "Staðbundið í vafranum, engin upphleðsla - 100% persónuvernd", "drag_drop_images": "Dragðu myndir hingað", "click_browse_p": "eða smelltu til að velja", "drag_drop": "Dragðu og slepptu", "click_browse": "eða smelltu", "feature_1_title": "🚀 Hratt og öruggt", "feature_1_desc": "Allar breytingar fara fram staðbundið í tækinu þínu.", "feature_2_title": "📉 Snjöll þjöppun", "feature_2_desc": "Minnka skráarstærð um allt að 80% án sjáanlegs gæðataps.", "feature_3_title": "⚡ Lotuvinnsla", "feature_3_desc": "Breyttu hundruðum mynda á nokkrum sekúndum.", "why_use_title": "Af hverju að nota ToWebP?", "why_use_p1": "ToWebP er persónuverndarvænn breytir sem keyrir alveg í vafranum þínum.", "why_use_p2": "Engar kökur, engin mæling.", "download": "SÆKJA",
        "processing": "Vinnsla...", "parsing_files": "Greining...", "waiting": "Bíður...", "total_saved_prefix": "Heildar Sparnaður:", "saved": "sparað", "starting": "Ræsi..."
    },
    "lt": {
        "app_name": "ToWebP", "files": "failų", "total_saved_header": "Iš viso sutaupyta: ", "download_zip": "Atsisiųsti ZIP", "clear": "Išvalyti", "format": "Formatas", "quality": "Kokybė", "hero_title": "Geriausias ir greičiausias būdas konvertuoti vaizdus į WebP", "hero_subtitle": "Vietoje naršyklėje, be įkėlimo - 100% privatumas", "drag_drop_images": "Vilkite vaizdus čia", "click_browse_p": "arba spustelėkite naršyti", "drag_drop": "Vilkti ir paleisti", "click_browse": "arba spustelėti", "feature_1_title": "🚀 Greita ir saugu", "feature_1_desc": "Visi konvertavimai vyksta vietoje jūsų įrenginyje.", "feature_2_title": "📉 Išmanus suspaudimas", "feature_2_desc": "Sumažinkite failo dydį iki 80% be matomo kokybės praradimo.", "feature_3_title": "⚡ Masinis apdorojimas", "feature_3_desc": "Konvertuokite šimtus vaizdų per kelias sekundes.", "why_use_title": "Kodėl naudoti ToWebP?", "why_use_p1": "ToWebP yra į privatumą orientuotas keitiklis, veikiantis tik jūsų naršyklėje.", "why_use_p2": "Jokių slapukų, jokio sekimo.", "download": "ATSISIŲSTI",
        "processing": "Apdorojama...", "parsing_files": "Analizuojama...", "waiting": "Laukiama...", "total_saved_prefix": "Iš Viso Sutaupyta:", "saved": "sutaupyta", "starting": "Paleidžiama..."
    },
    "lv": {
        "app_name": "ToWebP", "files": "faili", "total_saved_header": "Kopā ietaupīts: ", "download_zip": "Lejupielādēt ZIP", "clear": "Notīrīt", "format": "Formāts", "quality": "Kvalitāte", "hero_title": "Labākais un ātrākais veids, kā konvertēt attēlus uz WebP", "hero_subtitle": "Lokāli pārlūkprogrammā, bez augšupielādes - 100% privātums", "drag_drop_images": "Velciet attēlus šeit", "click_browse_p": "vai noklikšķiniet, lai pārlūkotu", "drag_drop": "Vilkt un nomest", "click_browse": "vai noklikšķināt", "feature_1_title": "🚀 Ātri un droši", "feature_1_desc": "Visi pārveidojumi notiek lokāli jūsu ierīcē.", "feature_2_title": "📉 Gudra saspiešana", "feature_2_desc": "Samaziniet faila lielumu līdz 80% bez redzama kvalitātes zuduma.", "feature_3_title": "⚡ Pakešu apstrāde", "feature_3_desc": "Konvertējiet simtiem attēlu sekundēs.", "why_use_title": "Kāpēc izmantot ToWebP?", "why_use_p1": "ToWebP ir privātuma orientēts pārveidotājs, kas darbojas pilnībā jūsu pārlūkprogrammā.", "why_use_p2": "Bez sīkfailiem, bez izsekošanas.", "download": "LEJUPIELĀDĒT",
        "processing": "Apstrāde...", "parsing_files": "Analīze...", "waiting": "Gaida...", "total_saved_prefix": "Kopā Ietaupīts:", "saved": "ietaupīts", "starting": "Sāk..."
    },
    "no": {
        "app_name": "ToWebP", "files": "filer", "total_saved_header": "Totalt spart: ", "download_zip": "Last ned ZIP", "clear": "Tøm", "format": "Format", "quality": "Kvalitet", "hero_title": "Den beste og raskeste måten å konvertere bilder til WebP", "hero_subtitle": "Lokalt i nettleseren, ingen opplasting - 100% personvern", "drag_drop_images": "Dra bilder hit", "click_browse_p": "eller klikk for å bla gjennom", "drag_drop": "Dra og slipp", "click_browse": "eller klikk", "feature_1_title": "🚀 Rask og sikker", "feature_1_desc": "Alle konverteringer skjer lokalt på enheten din.", "feature_2_title": "📉 Smart komprimering", "feature_2_desc": "Reduser filstørrelsen med opptil 80% uten synlig kvalitetstap.", "feature_3_title": "⚡ Batchbehandling", "feature_3_desc": "Konverter hundrevis av bilder på sekunder.", "why_use_title": "Hvorfor bruke ToWebP?", "why_use_p1": "ToWebP er en personvernfokusert konverterer som kjører helt i nettleseren din.", "why_use_p2": "Ingen informasjonskapsler, ingen sporing.", "download": "LAST NED",
        "processing": "Behandler...", "parsing_files": "Analyserer...", "waiting": "Venter...", "total_saved_prefix": "Totalt Spart:", "saved": "spart", "starting": "Starter..."
    },
    "sk": {
        "app_name": "ToWebP", "files": "súborov", "total_saved_header": "Celkovo ušetrené: ", "download_zip": "Stiahnuť ZIP", "clear": "Vymazať", "format": "Formát", "quality": "Kvalita", "hero_title": "Najlepší a najrýchlejší spôsob prevodu obrázkov do WebP", "hero_subtitle": "Lokálne v prehliadači, žiadne nahrávanie - 100% súkromie", "drag_drop_images": "Presuňte sem obrázky", "click_browse_p": "alebo kliknite pre prehľadávanie", "drag_drop": "Presunúť a pustiť", "click_browse": "alebo klikni", "feature_1_title": "🚀 Rýchle a bezpečné", "feature_1_desc": "Všetky prevody prebiehajú lokálne na vašom zariadení.", "feature_2_title": "📉 Inteligentná kompresia", "feature_2_desc": "Zmenšite veľkosť súboru až o 80 % bez viditeľnej straty kvality.", "feature_3_title": "⚡ Hromadné spracovanie", "feature_3_desc": "Preveďte stovky obrázkov v priebehu sekúnd.", "why_use_title": "Prečo používať ToWebP?", "why_use_p1": "ToWebP je konvertor zameraný na súkromie bežiaci vo vašom prehliadači.", "why_use_p2": "Žiadne cookies, žiadne sledovanie.", "download": "STIAHNUŤ",
        "processing": "Spracovanie...", "parsing_files": "Načítanie...", "waiting": "Čakanie...", "total_saved_prefix": "Celkovo Ušetrené:", "saved": "ušetrené", "starting": "Spúšťanie..."
    },
    "sl": {
        "app_name": "ToWebP", "files": "datoteke", "total_saved_header": "Skupaj prihranjeno: ", "download_zip": "Prenesi ZIP", "clear": "Počisti", "format": "Format", "quality": "Kakovost", "hero_title": "Najboljši in najhitrejši način za pretvorbo slik v WebP", "hero_subtitle": "Lokalno v brskalniku, brez nalaganja - 100% zasebnost", "drag_drop_images": "Povlecite slike sem", "click_browse_p": "ali kliknite za brskanje", "drag_drop": "Povleci in spusti", "click_browse": "ali klikni", "feature_1_title": "🚀 Hitro in varno", "feature_1_desc": "Vse pretvorbe potekajo lokalno na vaši napravi.", "feature_2_title": "📉 Pametno stiskanje", "feature_2_desc": "Zmanjšajte velikost datoteke do 80 % brez vidne izgube kakovosti.", "feature_3_title": "⚡ Paketna obdelava", "feature_3_desc": "Pretvori na stotine slik v nekaj sekundah.", "why_use_title": "Zakaj uporabljati ToWebP?", "why_use_p1": "ToWebP je pretvornik, osredotočen na zasebnost, ki deluje v celoti v vašem brskalniku.", "why_use_p2": "Brez piškotkov, brez sledenja.", "download": "PRENESI",
        "processing": "Obdelava...", "parsing_files": "Analiza...", "waiting": "Čakanje...", "total_saved_prefix": "Skupaj Prihranjeno:", "saved": "prihranjeno", "starting": "Zagon..."
    }
};

function getBrowserLanguage() {
    const lang = navigator.language || navigator.userLanguage;
    return lang.split('-')[0];
}

function applyTranslations(lang = "en") {
    const selectedLang = translations[lang] ? lang : "en";
    const t = translations[selectedLang];
    
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key]) {
            // Use textContent to completely replace the content without duplication
            el.textContent = t[key];
        }
    });
    document.documentElement.lang = selectedLang;
}

window.i18n = {
    t: (key, lang = getBrowserLanguage()) => {
        const selectedLang = translations[lang] ? lang : "en";
        return translations[selectedLang][key] || translations["en"][key] || key;
    },
    apply: applyTranslations,
    getLang: getBrowserLanguage
};
