const translations = {
    "en": {
        "app_name": "toWeb<span>P</span>.dev", "files": "files", "total_saved_header": "Total Saved: ", "download_zip": "Download ZIP", "clear": "Clear", "format": "Format", "quality": "Quality", "hero_title": "Free Bulk Images to WebP Converter Online", "hero_subtitle": "Client side batch convert JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF to WEBP.<br/><strong>100% free</strong>, <strong>instant</strong> - leveraging all your cores, unlimited in your browser.<br/><span class='secondary-text'>No uploads - <strong>Your files stay Private</strong> and no bandwidth needed</span><br/><span class='secondary-text'>No cookies - No tracking!</span>", "drag_drop_images": "Drag & Drop images here", "click_browse_p": "or click to browse", "drag_drop": "Drag & Drop", "click_browse": "or click to browse",
        "feature_secure_title": "100% Secure & Private", "feature_secure_desc": "Unlike towebp.io and others, we run locally. Your images strictly never leave your device. No cloud uploads, no server storage, zero privacy risk.", "feature_fast_title": "Blazing Fast", "feature_fast_desc": "Utilize your computer's full power. Batch convert hundreds of JPEG, PNG, or AVIF images to WebP in seconds—faster than any server-side converter.", "feature_smart_title": "Smart Optimization", "feature_smart_desc": "Reduce file size by up to 80% while maintaining visual quality. Perfect for improving Core Web Vitals and SEO rankings for your own website.",
        "howto_title": "How to Convert Images to WebP", "step_1_title": "Upload or Drag & Drop", "step_1_desc": "Select your PNG, JPEG, or JPG images and drop them into the converter area.", "step_2_title": "Automatic Conversion", "step_2_desc": "ToWebP instantly processes your files locally using advanced browser technology.", "step_3_title": "Download & Save", "step_3_desc": "Download your optimized WebP files individually or as a ZIP archive.",
        "seo_comp_title": "Why Choose ToWebP vs Others?", "seo_comp_desc": "Many converters like towebp.io upload your sensitive photos to a remote server. This creates a privacy risk and slows down the process with upload/download times. ToWebP operates differently: it's a Progressive Web App (PWA) that processes images directly in your browser memory. This means military-grade privacy (the data never touches the internet) and instant speeds.", "seo_ranking_title": "WebP for Better SEO", "seo_ranking_desc": "Google explicitly favors fast-loading websites. Converting your PNGs and JPEGs to modern WebP format can significantly reduce page weight, improve LCP (Largest Contentful Paint), and boost your site's SEO ranking. ToWebP is the perfect tool for web developers and designers to bulk optimize assets.",
        "faq_title": "Frequently Asked Questions", "faq_1_q": "Is my data safe?", "faq_1_a": "Yes, 100%. Unlike other converters, ToWebP runs client-side. Your images never leave your computer.", "faq_2_q": "Can I convert images offline?", "faq_2_a": "Absolutely. ToWebP is PWA-enabled. You can install it and use it without an internet connection.", "faq_3_q": "What formats are supported?", "faq_3_a": "We support converting from JPG, JPEG, PNG, BMP, and GIF (static) to WebP format.", "faq_4_q": "Is it free?", "faq_4_a": "Yes, ToWebP is completely free with no daily limits or watermarks.", "why_use_title": "Why use ToWebP?", "why_use_p1": "ToWebP is a privacy-first image converter that runs entirely in your browser. Unlike other online converters, we do not upload your images to any server. This means your photos, designs, and documents remain 100% confidential and never leave your device.", "why_use_p2": "No Cookies, No Tracking. We believe in a clean and fast web. This site does not use persistent cookies or trackers, so you won't be pestered by consent banners. Just drag, drop, and convert with zero traces left behind.", "download": "DOWNLOAD",
        "gdpr_title": "100% GDPR Compliant & Worry Free", "gdpr_desc": "No Tracing. No Cookies. No Local Storage spying. We respect your User Rights by design. ToWebP is a pure utility tool that does one thing well without collecting a single byte of your data.",
        "processing": "Processing...", "parsing_files": "Parsing files...", "waiting": "Waiting...", "total_saved_prefix": "Total Saved:", "saved": "saved", "starting": "Starting...", "select_language": "Select Language"
    },
    "ro": {
        "app_name": "toWeb<span>P</span>.dev", "files": "fișiere", "total_saved_header": "Total Salvat: ", "download_zip": "Descarcă ZIP", "clear": "Șterge", "format": "Format", "quality": "Calitate", "hero_title": "Convertor Online Gratuit de Imagini în masă către WebP", "hero_subtitle": "Conversie locală în masă din JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF în WEBP.<br/><strong>100% gratuit</strong>, <strong>instantaneu</strong> - folosește toate nucleele tale, nelimitat în browser.<br/><span class='secondary-text'>Fără încărcări - <strong>Fișierele tale rămân private</strong> și nu necesită bandă de internet.</span><br/><span class='secondary-text'>Fără cookie-uri - Fără urmărire!</span>", "drag_drop_images": "Trage și plasează imaginile aici", "click_browse_p": "sau click pentru a selecta", "drag_drop": "Trage și plasează", "click_browse": "sau click pentru a selecta", "feature_1_title": "🚀 Rapid și Sigur", "feature_1_desc": "Toate conversiile au loc local pe dispozitivul tău. Imaginile nu părăsesc niciodată computerul tău, asigurând confidențialitate 100%.", "feature_2_title": "📉 Compresie Inteligentă", "feature_2_desc": "Redu dimensiunea fișierelor cu până la 80% fără pierderi vizibile de calitate. WebP este standardul modern pentru site-uri rapide.", "feature_3_title": "⚡ Procesare în Masă", "feature_3_desc": "Convertește sute de imagini în câteva secunde folosind procesare multi-core. Trage, plasează și gata.", "why_use_title": "De ce să folosești ToWebP?", "why_use_p1": "ToWebP este un convertor de imagini centrat pe confidențialitate care rulează în întregime în browserul tău. Spre deosebire de alte convertoare online, nu încărcăm imaginile tale pe niciun server. Acest lucru înseamnă că fotografiile, design-urile și documentele tale rămân 100% confidențiale.", "why_use_p2": "Fără module cookie, fără urmărire. Credem întrun web curat și rapid. Acest site nu folosește module cookie persistente sau trackere, deci nu vei fi deranjat de bannere de consimțământ.", "download": "DESCARCĂ",
        "processing": "Procesare...", "parsing_files": "Citire fișiere...", "waiting": "În așteptare...", "total_saved_prefix": "Total Salvat:", "saved": "salvat", "starting": "Se pornește...", "select_language": "Selectează Limba"
    },
    "fr": {
        "app_name": "toWeb<span>P</span>.dev", "files": "fichiers", "total_saved_header": "Économie Totale : ", "download_zip": "Télécharger ZIP", "clear": "Effacer", "format": "Format", "quality": "Qualité", "hero_title": "Convertisseur d'images en masse gratuit vers WebP en ligne", "hero_subtitle": "Conversion par lot côté client JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF vers WEBP.<br/><strong>100% gratuit</strong>, <strong>instantané</strong> - utilise tous vos cœurs, illimité în browser.<br/><span class='secondary-text'>Pas de téléchargement - <strong>Vos fichiers restent Privés</strong> și nu necesită bandă</span><br/><span class='secondary-text'>Pas de cookies - Pas de suivi !</span>", "drag_drop_images": "Glissez-déposez vos images ici", "click_browse_p": "ou cliquez pour parcourir", "drag_drop": "Glisser-déposer", "click_browse": "ou cliquez pour parcourir", "feature_1_title": "🚀 Rapide & Sécurisé", "feature_1_desc": "Toutes les conversions se font localement sur votre appareil. Vos images ne quittent jamais votre ordinateur.", "feature_2_title": "📉 Compression Intelligente", "feature_2_desc": "Réduisez la taille des fichiers jusqu'à 80% sans perte de qualité visible.", "feature_3_title": "⚡ Traitement par Lot", "feature_3_desc": "Convertissez des centaines d'images en quelques secondes.", "why_use_title": "Pourquoi utiliser ToWebP ?", "why_use_p1": "ToWebP est un convertisseur privé qui s'exécute entièrement dans votre navigateur.", "why_use_p2": "Pas de cookies, pas de suivi. Nous croyons en un web propre et rapide.", "download": "TÉLÉCHARGER",
        "processing": "Traitement...", "parsing_files": "Analyse des fichiers...", "waiting": "En attente...", "total_saved_prefix": "Économie Totale:", "saved": "sauvé", "starting": "Démarrage...", "select_language": "Choisir la Langue"
    },
    "de": {
        "app_name": "toWeb<span>P</span>.dev", "files": "Dateien", "total_saved_header": "Insgesamt gespart: ", "download_zip": "ZIP herunterladen", "clear": "Löschen", "format": "Format", "quality": "Qualität", "hero_title": "Kostenloser Online-Bulk-Bilder-zu-WebP-Konverter", "hero_subtitle": "Clientseitige Stapelkonvertierung von JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF zu WEBP.<br/><strong>100% kostenlos</strong>, <strong>sofort</strong> - nutzt all Ihre Kerne, unbegrenzt in Ihrem Browser.<br/><span class='secondary-text'>Kein Upload - <strong>Ihre Dateien bleiben privat</strong> und bandbreitenschonend</span><br/><span class='secondary-text'>Keine Cookies - Kein Tracking!</span>", "drag_drop_images": "Bilder hierher ziehen", "click_browse_p": "oder klicken zum Durchsuchen", "drag_drop": "Drag & Drop", "click_browse": "oder klicken", "feature_1_title": "🚀 Schnell & Sicher", "feature_1_desc": "Alle Konvertierungen finden lokal auf Ihrem Gerät statt.", "feature_2_title": "📉 Intelligente Kompression", "feature_2_desc": "Bis zu 80% kleinere Dateien ohne Qualitätsverlust.", "feature_3_title": "⚡ Stapelverarbeitung", "feature_3_desc": "Hunderte Bilder in Sekunden konvertieren.", "why_use_title": "Warum ToWebP nutzen?", "why_use_p1": "ToWebP ist ein privater Konverter, der komplett im Browser läuft.", "why_use_p2": "Keine Cookies, kein Tracking.", "download": "DOWNLOAD",
        "processing": "Verarbeitung...", "parsing_files": "Dateien werden gelesen...", "waiting": "Warten...", "total_saved_prefix": "Insgesamt gespart:", "saved": "gespart", "starting": "Startet..."
    },
    "es": {
        "app_name": "toWeb<span>P</span>.dev", "files": "archivos", "total_saved_header": "Ahorro total: ", "download_zip": "Descargar ZIP", "clear": "Limpiar", "format": "Formato", "quality": "Calidad", "hero_title": "Convertidor masivo gratuito de imágenes a WebP en línea", "hero_subtitle": "Conversión por lotes del lado del cliente JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF a WEBP.<br/><strong>100% gratis</strong>, <strong>instantáneo</strong>: aprovecha toți procesorii tăi, nelimitat în browser.<br/><span class='secondary-text'>Sin subidas: <strong>tus archivos se mantienen privados</strong> și fără consum de bandă</span><br/><span class='secondary-text'>Sin cookies - ¡Sin rastreo!</span>", "drag_drop_images": "Arrastra las imágenes aquí", "click_browse_p": "o haz clic para buscar", "drag_drop": "Arrastrar y soltar", "click_browse": "o haz clic", "feature_1_title": "🚀 Rápido y Seguro", "feature_1_desc": "Todas las conversiones ocurren localmente en tu dispositivo.", "feature_2_title": "📉 Compresión Inteligente", "feature_2_desc": "Reduce el tamaño hasta un 80% sin pérdida visible.", "feature_3_title": "⚡ Procesamiento por Lote", "feature_3_desc": "Convierte cientos de imágenes en segundos.", "why_use_title": "¿Por qué usar ToWebP?", "why_use_p1": "ToWebP es un convertidor privado que funciona en tu navegador.", "why_use_p2": "Sin cookies ni rastreo.", "download": "DESCARGAR",
        "processing": "Procesando...", "parsing_files": "Analizando archivos...", "waiting": "Esperando...", "total_saved_prefix": "Ahorro Total:", "saved": "ahorrado", "starting": "Iniciando..."
    },
    "it": {
        "app_name": "toWeb<span>P</span>.dev", "files": "file", "total_saved_header": "Risparmio totale: ", "download_zip": "Scarica ZIP", "clear": "Pulisci", "format": "Formato", "quality": "Qualità", "hero_title": "Convertitore batch gratuito di immagini in WebP online", "hero_subtitle": "Conversione batch lato client JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF în WEBP.<br/><strong>100% gratuito</strong>, <strong>istantaneo</strong> - sfrutta tutti i tăi nuclee, illimitato nel browser.<br/><span class='secondary-text'>Nessun caricamento - <strong>I tuoi file rimangono privati</strong> e zero consumo di banda</span><br/><span class='secondary-text'>Niente cookie - Nessun tracciamento!</span>", "drag_drop_images": "Trascina le immagini qui", "click_browse_p": "o clicca per sfogliare", "drag_drop": "Trascina e rilascia", "click_browse": "o clicca", "feature_1_title": "🚀 Veloce & Sicuro", "feature_1_desc": "Tutte le conversioni avvengono localmente sul tuo dispositivo.", "feature_2_title": "📉 Compressione Intelligente", "feature_2_desc": "Riduci le dimensioni fino all'80% senza perdita visibile.", "feature_3_title": "⚡ Elaborazione a Lotti", "feature_3_desc": "Converti centinaia di immagini in pochi secondi.", "why_use_title": "Perché usare ToWebP?", "why_use_p1": "ToWebP è un convertitore privato che gira nel tuo browser.", "why_use_p2": "Niente cookie, niente tracciamento.", "download": "SCARICA",
        "processing": "Elaborazione...", "parsing_files": "Analisi file...", "waiting": "In attesa...", "total_saved_prefix": "Risparmio Totale:", "saved": "risparmiato", "starting": "Avvio..."
    },
    "pt": {
        "app_name": "toWeb<span>P</span>.dev", "files": "arquivos", "total_saved_header": "Total economizado: ", "download_zip": "Baixar ZIP", "clear": "Limpar", "format": "Formato", "quality": "Qualidade", "hero_title": "Conversor em massa gratuito de imagens para WebP on-line", "hero_subtitle": "Conversão em lote no lado do cliente JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF pentru WEBP.<br/><strong>100% gratuito</strong>, <strong>instantâneo</strong> - aproveitando todos os seus nucleos, ilimitado no seu navegador.<br/><span class='secondary-text'>Sem uploads - <strong>Seus arquivos permanecem privados</strong> e sem necessidade de banda</span><br/><span class='secondary-text'>Sem cookies - Sem rastreamento!</span>", "drag_drop_images": "Arraste as imagens para cá", "click_browse_p": "ou clique para navegar", "drag_drop": "Arrastar e soltar", "click_browse": "ou clique", "feature_1_title": "🚀 Rápido e Seguro", "feature_1_desc": "Todas as conversões ocorrem localmente no seu dispositivo.", "feature_2_title": "📉 Compressão Inteligente", "feature_2_desc": "Reduza o tamanho em até 80% sem perda visível.", "feature_3_title": "⚡ Processamento em Lote", "feature_3_desc": "Converta centenas de imagens em segundos.", "why_use_title": "Por que usar ToWebP?", "why_use_p1": "ToWebP é um conversor privado que roda no seu navegador.", "why_use_p2": "Sem cookies, sem rastreamento.", "download": "BAIXAR",
        "processing": "Processando...", "parsing_files": "Analisando arquivos...", "waiting": "Aguardando...", "total_saved_prefix": "Total Economizado:", "saved": "economizado", "starting": "Iniciando..."
    },
    "nl": {
        "app_name": "toWeb<span>P</span>.dev", "files": "bestanden", "total_saved_header": "Totaal bespaard: ", "download_zip": "Download ZIP", "clear": "Wissen", "format": "Formaat", "quality": "Kwaliteit", "hero_title": "Gratis online batch-converter voor afbeeldingen naar WebP", "hero_subtitle": "Client-side batch-conversie JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF naar WEBP.<br/><strong>100% gratis</strong>, <strong>direct</strong> - benut al tăi nucleele, onbeperkt in je browser.<br/><span class='secondary-text'>Geen uploads - <strong>Je bestanden blijven privé</strong> en geen bandbreedte nodig</span><br/><span class='secondary-text'>Geen cookies - Geen tracking!</span>", "drag_drop_images": "Sleep afbeeldingen hierheen", "click_browse_p": "of klik om te bladeren", "drag_drop": "Slepen en neerzetten", "click_browse": "of klik", "feature_1_title": "🚀 Snel & Veilig", "feature_1_desc": "Alle conversies vinden lokaal plaats op uw apparaat.", "feature_2_title": "📉 Slimme Compressie", "feature_2_desc": "Verklein bestanden tot 80% zonder zichtbaar kwaliteitsverlies.", "feature_3_title": "⚡ Batchverwerking", "feature_3_desc": "Converteer honderden afbeeldingen in seconden.", "why_use_title": "Waarom ToWebP gebruiken?", "why_use_p1": "ToWebP is een privacyvriendelijke converter die in uw browser werkt.", "why_use_p2": "Geen cookies, geen tracking.", "download": "DOWNLOADEN",
        "processing": "Verwerken...", "parsing_files": "Bestanden analyseren...", "waiting": "Wachten...", "total_saved_prefix": "Totaal Bespaard:", "saved": "bespaard", "starting": "Starten..."
    },
    "el": {
        "app_name": "toWeb<span>P</span>.dev", "files": "αρχεία", "total_saved_header": "Συνολική εξοικονόμηση: ", "download_zip": "Λήψη ZIP", "clear": "Καθαρισμός", "format": "Μορφή", "quality": "Ποιότητα", "hero_title": "Δωρεάν μαζική μετατροπή εικόνων σε WebP online", "hero_subtitle": "Μετατροπή παρτίδας από την πλευρά του πελάτη JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF σε WEBP.<br/><strong>100% δωρεάν</strong>, <strong>άμεση</strong> - αξιοποιώντας όλους τους πυρήνες σας, απεριόριστα στο πρόγραμμα περιήγησής σας.<br/><span class='secondary-text'>Χωρίς μεταφορτώσεις - <strong>Τα αρχεία σας παραμένουν ιδιωτικά</strong> και δεν απαιτείται εύρος ζώνης</span><br/><span class='secondary-text'>Χωρίς cookies - Χωρίς παρακολούθηση!</span>", "drag_drop_images": "Σύρετε τις εικόνες εδώ", "click_browse_p": "ή κάντε κλικ για περιήγηση", "drag_drop": "Σύρετε και αφήστε", "click_browse": "ή κάντε κλικ", "feature_1_title": "🚀 Γρήγορο & Ασφαλές", "feature_1_desc": "Όλες οι μετατροπές γίνονται τοπικά στη συσκευή σας.", "feature_2_title": "📉 Έξυπνη συμπίεση", "feature_2_desc": "Μειώστε το μέγεθος έως και 80% χωρίς ορατή απώλεια ποιότητας.", "feature_3_title": "⚡ Μαζική επεξεργασία", "feature_3_desc": "Μετατρέψτε εκατοντάδες εικόνες σε δευτερόλεπτα.", "why_use_title": "Γιατί να χρησιμοποιήσετε το ToWebP;", "why_use_p1": "Το ToWebP είναι ένας μετατροπέας με επίκεντρο την ιδιωτικότητα που τρέχει στο πρόγραμμα περιήγησης.", "why_use_p2": "Χωρίς cookies, χωρίς παρακολούθηση.", "download": "ΛΗΨΗ",
        "processing": "Επεξεργασία...", "parsing_files": "Ανάλυση αρχείων...", "waiting": "Αναμονή...", "total_saved_prefix": "Συνολική Εξοικονόμηση:", "saved": "εξοικονομήθηκαν", "starting": "Έναρξη..."
    },
    "hu": {
        "app_name": "toWeb<span>P</span>.dev", "files": "fájl", "total_saved_header": "Összesen megtakarítva: ", "download_zip": "ZIP letöltése", "clear": "Törlés", "format": "Formátum", "quality": "Minőség", "hero_title": "Ingyenes online tömeges kép-WebP konvertáló", "hero_subtitle": "Kliensoldali batch konvertálás JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF formátumokból WEBP-be.<br/><strong>100% ingyenes</strong>, <strong>azonnali</strong> - minden magot kihasználva, korlátlanul a böngészőjében.<br/><span class='secondary-text'>Nincs feltöltés - <strong>A fájljai privátak maradnak</strong> és nem igényel plusz sávszélességet</span><br/><span class='secondary-text'>Nincsenek sütik - Nincs nyomon követés!</span>", "drag_drop_images": "Húzza ide a képeket", "click_browse_p": "vagy kattintson a tallózáshoz", "drag_drop": "Húzd és ejtsd", "click_browse": "vagy kattints", "feature_1_title": "🚀 Gyors és biztonságos", "feature_1_desc": "Minden átalakítás helyben történik az eszközén.", "feature_2_title": "📉 Intelligens tömörítés", "feature_2_desc": "Csökkentse a fájlméretet akár 80%-kal látható minőségromlás nélkül.", "feature_3_title": "⚡ Kötegelt feldolgozás", "feature_3_desc": "Konvertáljon több száz képet másodpercek alatt.", "why_use_title": "Miért használja a ToWebP-t?", "why_use_p1": "A ToWebP egy adatvédelem-központú konvertáló, amely a böngészőjében fut.", "why_use_p2": "Nincsenek sütik, nincs nyomon követés.", "download": "LETÖLTÉS",
        "processing": "Feldolgozás...", "parsing_files": "Fájlok elemzése...", "waiting": "Várakozás...", "total_saved_prefix": "Összesen Megtakarítva:", "saved": "megtakarítva", "starting": "Indítás..."
    },
    "pl": {
        "app_name": "toWeb<span>P</span>.dev", "files": "plików", "total_saved_header": "Łącznie zaoszczędzono: ", "download_zip": "Pobierz ZIP", "clear": "Wyczyść", "format": "Format", "quality": "Jakość", "hero_title": "Darmowy masowy konwerter obrazów do WebP online", "hero_subtitle": "Konwersja wsadowa po stronie klienta JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF do WEBP.<br/><strong>100% za darmo</strong>, <strong>natychmiastowo</strong> - wykorzystując wszystkie Twoje rdzenie, bez limitów w przeglądarce.<br/><span class='secondary-text'>Bez przesyłania - <strong>Twoje pliki pozostają prywatne</strong> i bez użycia transferu</span><br/><span class='secondary-text'>Bez ciasteczek - Bez śledzenia!</span>", "drag_drop_images": "Przeciągnij obrazy tutaj", "click_browse_p": "lub kliknij, aby przeglądać", "drag_drop": "Przeciągnij i upuść", "click_browse": "lub kliknij", "feature_1_title": "🚀 Szybko i bezpiecznie", "feature_1_desc": "Wszystkie konwersje odbywają się lokalnie na Twoim urządzeniu.", "feature_2_title": "📉 Inteligentna kompresja", "feature_2_desc": "Zmniejsz rozmiar pliku nawet o 80% bez widocznej utraty jakości.", "feature_3_title": "⚡ Przetwarzanie wsadowe", "feature_3_desc": "Konwertuj setki obrazów w kilka sekund.", "why_use_title": "Dlaczego warto korzystać z ToWebP?", "why_use_p1": "ToWebP to konwerter chroniący prywatność, który działa w całości w Twojej przeglądarce.", "why_use_p2": "Bez ciasteczek, bez śledzenia.", "download": "POBIERZ",
        "processing": "Przetwarzanie...", "parsing_files": "Analizowanie plików...", "waiting": "Oczekiwanie...", "total_saved_prefix": "Łącznie Zaoszczędzono:", "saved": "zaoszczędzono", "starting": "Uruchamianie..."
    },
    "ar": {
        "app_name": "toWeb<span>P</span>.dev", "files": "ملفات", "total_saved_header": "إجمالي التوفير: ", "download_zip": "تحميل ZIP", "clear": "مسح", "format": "تنسيق", "quality": "جودة", "hero_title": "محول صور WebP مجاني بالجملة عبر الإنترنت", "hero_subtitle": "تحويل دفعة من JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF إلى WEBP من جانب العميل.<br/><strong>100% مجاني</strong>، <strong>فوري</strong> - يستفيد من جميع أنويتك، غير محدود في متصفحك.<br/><span class='secondary-text'>لا توجد عمليات تحميل - <strong>تبقى ملفاتك خاصة</strong> ولا يلزم نطاق ترددي</span><br/><span class='secondary-text'>لا توجد ملفات تعريف ارتباط - لا يوجد تتبع!</span>", "drag_drop_images": "اسحب وأفلت الصور هنا", "click_browse_p": "أو انقر للتصفح", "drag_drop": "سحب وإفلات", "click_browse": "أو انقر للتصفح", "feature_1_title": "🚀 سريع وآمن", "feature_1_desc": "تتم جميع التحويلات محليًا على جهازك.", "feature_2_title": "📉 ضغط ذكي", "feature_2_desc": "تقليل حجم الملف بنسبة تصل إلى 80٪ بدون فقدان جودة ملحوظ.", "feature_3_title": "⚡ معالجة مجمعة", "feature_3_desc": "تحويل مئات الصور في ثوانٍ.", "why_use_title": "لماذا تستخدم ToWebP؟", "why_use_p1": "ToWebP هو محول صور يهتم بالخصوصية يعمل بالكامل σε متصفحك.", "why_use_p2": "بدون ملفات تعريف ارتباط، بدون تتبع.", "download": "تحميل",
        "processing": "جاري المعالجة...", "parsing_files": "جاري تحليل الملفات...", "waiting": "في الانتظار...", "total_saved_prefix": "إجمالي التوفير:", "saved": "تم توفيره", "starting": "جاري البدء..."
    },
    "bg": {
        "app_name": "toWeb<span>P</span>.dev", "files": "файла", "total_saved_header": "Общо спестени: ", "download_zip": "Изтегли ZIP", "clear": "Изчисти", "format": "Формат", "quality": "Качество", "hero_title": "Безплатен онлайн масов конвертор на изображения в WebP", "hero_subtitle": "Пакетно конвертиране от страна на клиента JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF в WEBP.<br/><strong>100% безплатно</strong>, <strong>мигновено</strong> - използвайки всички ваши ядра, неограничено във вашия браузър.<br/><span class='secondary-text'>Без качвания - <strong>Файловете ви остават поверителни</strong> и без нужда от трафик</span><br/><span class='secondary-text'>Без бисквитки - Без проследяване!</span>", "drag_drop_images": "Плъзнете изображенията тук", "click_browse_p": "или кликнете за преглед", "drag_drop": "Πлъзгане и пускаνε", "click_browse": "или кликнете", "feature_1_title": "🚀 Бързо и сигурнο", "feature_1_desc": "Всички конвертирания се случват локално на вашеτο устройство.", "feature_2_title": "📉 Интелигентна компресия", "feature_2_desc": "Намалете размера с до 80% без видима загуба на качество.", "feature_3_title": "⚡ Групова обработка", "feature_3_desc": "Конвертирайте стотици изображения за секунди.", "why_use_title": "Защо да използвате ToWebP?", "why_use_p1": "ToWebP е конвертор, фокусиран върху поверителността, който работи изцяло във вашия браузър.", "why_use_p2": "Без бисквитки, без проследяване.", "download": "ИЗТЕГЛИ",
        "processing": "Обработка...", "parsing_files": "Анализиране на файлове...", "waiting": "Изчакване...", "total_saved_prefix": "Общо Спестени:", "saved": "спестени", "starting": "Стартиране..."
    },
    "ja": {
        "app_name": "toWeb<span>P</span>.dev", "files": "ファイル", "total_saved_header": "合計節約量: ", "download_zip": "ZIPをダウンロード", "clear": "クリア", "format": "形式", "quality": "画質", "hero_title": "無料のWebP一括変換ツール", "hero_subtitle": "クライアント側でJPG、PNG、GIF、SVG、ICO、BMP、TIFF、HEIC、AVIFをWebPに一括変換。<br/><strong>100%無料</strong>、<strong>即時</strong> - すべてのコアを活用し、ブラウザで無制限に利用可能。<br/><span class='secondary-text'>アップロード不要 - <strong>ファイルはプライベートに保たれ</strong>、帯域幅も不要</span><br/><span class='secondary-text'>Cookieなし - 追跡なし！</span>", "drag_drop_images": "ここに画像をドラッグ＆ドロップ", "click_browse_p": "またはクリックして選択", "drag_drop": "ドラッグ＆ドロップ", "click_browse": "またはクリック", "feature_1_title": "🚀 高速で安全", "feature_1_desc": "すべての変換はデバイス上でローカルに行われます。", "feature_2_title": "📉 スマート圧縮", "feature_2_desc": "画質を維持したまま、ファイルサイズを最大80%削減します。", "feature_3_title": "⚡ 一括処理", "feature_3_desc": "数百枚の画像を数秒で変換できます。", "why_use_title": "なぜToWebPを使うのか？", "why_use_p1": "ToWebPは、ブラウザだけで動作するプライバシー重視の画像コンバーターです。", "why_use_p2": "Cookieなし、追跡なし。", "download": "ダウンロード",
        "processing": "処理中...", "parsing_files": "ファイルを解析中...", "waiting": "待機中...", "total_saved_prefix": "合計節約量:", "saved": "節約済み", "starting": "開始中..."
    },
    "zh": {
        "app_name": "toWeb<span>P</span>.dev", "files": "个文件", "total_saved_header": "总共节省：", "download_zip": "下载 ZIP", "clear": "清除", "format": "格式", "quality": "质量", "hero_title": "将图片转换为 WebP 的最佳且最快的方式", "hero_subtitle": "客户端处理，无需上传 - 100% 隐私保护", "drag_drop_images": "将图片拖放到此处", "click_browse_p": "或点击浏览", "drag_drop": "拖放", "click_browse": "或点击", "feature_1_title": "🚀 快速且安全", "feature_1_desc": "所有转换均在您的设备上本地运行。", "feature_2_title": "📉 智能压缩", "feature_2_desc": "在不损失可见画质的情况下，可减少高达 80% 的文件大小。", "feature_3_title": "⚡ 批量处理", "feature_3_desc": "数秒内转换数百张图片。", "why_use_title": "为什么选择 ToWebP？", "why_use_p1": "ToWebP 是一款完全在浏览器中运行的隐私优先图片转换器。", "why_use_p2": "无 Cookie，无追踪。", "download": "下载",
        "processing": "处理中...", "parsing_files": "解析文件...", "waiting": "等待中...", "total_saved_prefix": "总共节省:", "saved": "已节省", "starting": "开始..."
    },
    "cs": {
        "app_name": "toWeb<span>P</span>.dev", "files": "souborů", "total_saved_header": "Celkem ušetřeno: ", "download_zip": "Stáhnout ZIP", "clear": "Vymazat", "format": "Formát", "quality": "Kvalita", "hero_title": "Bezplatný hromadný online převodník obrázků do WebP", "hero_subtitle": "Dávková konverze na straně klienta JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF do WEBP.<br/><strong>100% zdarma</strong>, <strong>okamžitě</strong> - využití všech vašich jader, neomezeně v prohlížeči.<br/><span class='secondary-text'>Žádné nahrávání - <strong>Vaše soubory zůstávají soukromé</strong> a bez nároků na šířku pásma</span><br/><span class='secondary-text'>Žádné cookies - Žádné sledování!</span>", "drag_drop_images": "Přetáhněte sem obrázky", "click_browse_p": "nebo klikněte pro procházení", "drag_drop": "Přetáhnout", "click_browse": "nebo klikněte", "feature_1_title": "🚀 Rychlé a bezpečné", "feature_1_desc": "Všechny převody probíhají lokálně na vašem zařízení.", "feature_2_title": "📉 Chytrá komprese", "feature_2_desc": "Zmenšete velikost až o 80 % bez viditelné ztráty kvality.", "feature_3_title": "⚡ Hromadné zpracování", "feature_3_desc": "Převeďte stovky obrázků během sekund.", "why_use_title": "Proč používat ToWebP?", "why_use_p1": "ToWebP je konvertor zaměřený na soukromí běžící v prohlížeči.", "why_use_p2": "Žádné cookies, žádné sledování.", "download": "STÁHNOUT",
        "processing": "Zpracování...", "parsing_files": "Načítání...", "waiting": "Čekání...", "total_saved_prefix": "Celkem Ušetřeno:", "saved": "ušetřeno", "starting": "Spouštění..."
    },
    "da": {
        "app_name": "toWeb<span>P</span>.dev", "files": "filer", "total_saved_header": "Samlet sparet: ", "download_zip": "Hent ZIP", "clear": "Ryd", "format": "Format", "quality": "Kvalitet", "hero_title": "Gratis online batch-konvertering fra billeder til WebP", "hero_subtitle": "Client-side batch-konvertering JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF til WEBP.<br/><strong>100% gratis</strong>, <strong>øjeblikkeligt</strong> - udnytter alle dine kerner, ubegrænset i din browser.<br/><span class='secondary-text'>Ingen uploads - <strong>Dine filer forbliver private</strong> og intet båndbreddeforbrug</span><br/><span class='secondary-text'>Ingen cookies - Ingen tracking!</span>", "drag_drop_images": "Træk billeder herhen", "click_browse_p": "eller klik for at gennemse", "drag_drop": "Træk og slip", "click_browse": "eller klik", "feature_1_title": "🚀 Hurtig & Sikker", "feature_1_desc": "Alle konverteringer sker lokalt på din enhed.", "feature_2_title": "📉 Smart Komprimering", "feature_2_desc": "Reducer filstørrelsen op til 80% ohne synligt kvalitetstab.", "feature_3_title": "⚡ Batch-behandling", "feature_3_desc": "Konverter hundredvis af billeder på sekunder.", "why_use_title": "Hvorfor bruge ToWebP?", "why_use_p1": "ToWebP kører udelukkende i din browser.", "why_use_p2": "Ingen cookies, ingen tracking.", "download": "HENT",
        "processing": "Behandler...", "parsing_files": "Analyserer...", "waiting": "Venter...", "total_saved_prefix": "Samlet Sparet:", "saved": "sparet", "starting": "Starter..."
    },
    "sv": {
        "app_name": "toWeb<span>P</span>.dev", "files": "filer", "total_saved_header": "Totalt sparat: ", "download_zip": "Ladda ner ZIP", "clear": "Rensa", "format": "Format", "quality": "Kvalitet", "hero_title": "Gratis online batch-konverterare för bilder till WebP", "hero_subtitle": "Klient-sida batch-konvertering JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF till WEBP.<br/><strong>100% gratis</strong>, <strong>omedelbart</strong> - utnyttjar alla dina kärnor, obegränsat i din webbläsare.<br/><span class='secondary-text'>Inga uppladdningar - <strong>Dina filer förblir privata</strong> och ingen bandbredd behövs</span><br/><span class='secondary-text'>Inga cookies - Ingen spårning!</span>", "drag_drop_images": "Dra bilder hit", "click_browse_p": "eller klicka för att bläddra", "drag_drop": "Dra och släpp", "click_browse": "or klicka", "feature_1_title": "🚀 Snabb & Säker", "feature_1_desc": "Alla konverteringar sker lokalt på din enhed.", "feature_2_title": "📉 Smart Komprimering", "feature_2_desc": "Minska filstorleken upp till 80% utan synlig kvalitetsförlust.", "feature_3_title": "⚡ Batchhantering", "feature_3_desc": "Konvertera hundratals bilder på sekunder.", "why_use_title": "Varför använda ToWebP?", "why_use_p1": "ToWebP körs helt i din webbläsare.", "why_use_p2": "Inga cookies, ingen spårning.", "download": "LADDA NER",
        "processing": "Bearbetar...", "parsing_files": "Tolkar...", "waiting": "Väntar...", "total_saved_prefix": "Totalt Sparat:", "saved": "sparat", "starting": "Startar..."
    },
    "fi": {
        "app_name": "toWeb<span>P</span>.dev", "files": "tiedostoa", "total_saved_header": "Säästetty yhteensä: ", "download_zip": "Lataa ZIP", "clear": "Tyhjennä", "format": "Muoto", "quality": "Laatu", "hero_title": "Ilmainen kuvien joukkokonvertteri WebP-muotoon verkossa", "hero_subtitle": "Asiakaspuolen joukkokonversio JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF WebP-muotoon.<br/><strong>100% ilmainen</strong>, <strong>välitön</strong> - hyödyntäen kaikkia ytimiäsi, rajoittamattomasti selaimessasi.<br/><span class='secondary-text'>Ei latauksia - <strong>Tiedostosi pysyvät yksityisinä</strong> eikä kaistanleveyttä tarvita</span><br/><span class='secondary-text'>Ei evästeitä - Ei seurantaa!</span>", "drag_drop_images": "Vedä kuvat tähän", "click_browse_p": "tai napsauta selataksesi", "drag_drop": "Vedä ja pudota", "click_browse": "tai napsauta", "feature_1_title": "🚀 Nopea & Turvallinen", "feature_1_desc": "Kaikki muunnokset tapahtuvat laitteellasi.", "feature_2_title": "📉 Älykäs pakkaus", "feature_2_desc": "Pienennä tiedostokokoa jopa 80% ilman näkyvää laatuhäviötä.", "feature_3_title": "⚡ Joukkokäsittely", "feature_3_desc": "Muunna satoja kuvia sekunneissa.", "why_use_title": "Miksi käyttää ToWebP:tä?", "why_use_p1": "ToWebP toimii kokonaan selaimessasi.", "why_use_p2": "Ei evästeitä, ei seurantaa.", "download": "LATAA",
        "processing": "Käsitellään...", "parsing_files": "Luetaan...", "waiting": "Odotetaan...", "total_saved_prefix": "Säästetty Yhteensä:", "saved": "säästetty", "starting": "Käynnistetään..."
    },
    "ru": {
        "app_name": "toWeb<span>P</span>.dev", "files": "файлов", "total_saved_header": "Всего сохранено: ", "download_zip": "Скачать ZIP", "clear": "Очистить", "format": "Формат", "quality": "Качество", "hero_title": "Бесплатный массовый онлайн-конвертер изображений в WebP", "hero_subtitle": "Пакетная конвертация на стороне клиента JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF в WEBP.<br/><strong>100% бесплатно</strong>, <strong>мгновенно</strong> — с использованием всех ваших ядер, без ограничений в браузере.<br/><span class='secondary-text'>Без загрузки на сервер — <strong>ваши файлы остаются конфиденциальными</strong> и без затрат трафика</span><br/><span class='secondary-text'>Без куки — без отслеживания!</span>", "drag_drop_images": "Перетащите изображения сюда", "click_browse_p": "или нажмите для выбора", "drag_drop": "Перетащить", "click_browse": "или выбрать", "feature_1_title": "🚀 Быстро и безопасно", "feature_1_desc": "Все преобразования происходят локально на вашем устройстве.", "feature_2_title": "📉 Умное сжатие", "feature_2_desc": "Уменьшите размер до 80% без видимой потери качества.", "feature_3_title": "⚡ Пакетная обработка", "feature_3_desc": "Конвертируйте сотни изображений за секунды.", "why_use_title": "Почему ToWebP?", "why_use_p1": "ToWebP работает полностью в вашем браузере.", "why_use_p2": "Без куки, без трекеров.", "download": "СКАЧАТЬ",
        "processing": "Обработка...", "parsing_files": "Анализ...", "waiting": "Ожидание...", "total_saved_prefix": "Всего сохранено:", "saved": "сохранено", "starting": "Запуск..."
    },
    "tr": {
        "app_name": "toWeb<span>P</span>.dev", "files": "dosya", "total_saved_header": "Toplam Tasarruf: ", "download_zip": "ZIP İndir", "clear": "Temizle", "format": "Format", "quality": "Kalite", "hero_title": "Ücretsiz Online Toplu Görüntüden WebP'ye Dönüştürücü", "hero_subtitle": "İstemci taraflı toplu dönüştürme JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF -> WEBP.<br/><strong>%100 ücretsiz</strong>, <strong>anında</strong> - tüm çekirdeklerinizi kullanarak, tarayıcınızda sınırsız.<br/><span class='secondary-text'>Yükleme yok - <strong>Dosyalarınız Gizli kalır</strong> ve bant genişliği gerekmez</span><br/><span class='secondary-text'>Çerez yok - Takip yok!</span>", "drag_drop_images": "Görselleri buraya sürükleyin", "click_browse_p": "veya göz atmak için tıklayın", "drag_drop": "Sürükle ve Bırak", "click_browse": "veya tıklayın", "feature_1_title": "🚀 Hızlı & Güvenli", "feature_1_desc": "Tüm dönüşümler cihazınızda yerel olarak gerçekleşir.", "feature_2_title": "📉 Akıllı Sıkıştırma", "feature_2_desc": "Görünür kalite kaybı olmadan boyutu %80'e kadar azaltın.", "feature_3_title": "⚡ Toplu İşlem", "feature_3_desc": "Saniyeler içinde yüzlerce görseli dönüştürün.", "why_use_title": "Neden ToWebP?", "why_use_p1": "ToWebP, tamamen tarayıcınızda çalışan gizlilik odaklı bir dönüştürücüdür.", "why_use_p2": "Çerez yok, izleme yok.", "download": "İNDİR",
        "processing": "İşleniyor...", "parsing_files": "Ayrıştırılıyor...", "waiting": "Bekleniyor...", "total_saved_prefix": "Toplam Tasarruf:", "saved": "tasarruf edildi", "starting": "Başlatılıyor..."
    },
    "et": {
        "app_name": "toWeb<span>P</span>.dev", "files": "faili", "total_saved_header": "Kokku säästetud: ", "download_zip": "Laadi alla ZIP", "clear": "Tühjenda", "format": "Vorming", "quality": "Kvaliteet", "hero_title": "Tasuta online-massipiltide WebP-ks teisendaja", "hero_subtitle": "Kliendipoolne partii teisendamine JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF-ist WEBP-ks.<br/><strong>100% tasuta</strong>, <strong>kohene</strong> - kasutades kõiki teie tuumi, piiramatult teie brauseris.<br/><span class='secondary-text'>Üleslaadimisi pole - <strong>Teie failid jäävad privaatseks</strong> ja ribalaiust pole vaja</span><br/><span class='secondary-text'>Küpsiseid pole - Jälitamine puudub!</span>", "drag_drop_images": "Lohista pildid siia", "click_browse_p": "või klõpsa sirvimiseks", "drag_drop": "Lohista ja aseta", "click_browse": "või klõpsa", "feature_1_title": "🚀 Kiire ja turvaline", "feature_1_desc": "Kõik teisendused toimuvad kohapeal sinu seadmes.", "feature_2_title": "📉 Nutikas tihendamine", "feature_2_desc": "Vähenda failimahtu kuni 80% ilma nähtava kvaliteedikaota.", "feature_3_title": "⚡ Hulgi töötlemine", "feature_3_desc": "Teisenda sadu pilte sekunditega.", "why_use_title": "Miks kasutada ToWebP-d?", "why_use_p1": "ToWebP on privaatsusele keskendunud konverter, mis töötab täielikult sinu brauseris.", "why_use_p2": "Ei küpsiseid ega jälgimist.", "download": "LAADI ALLA",
        "processing": "Töötlemine...", "parsing_files": "Analüüsimine...", "waiting": "Ootel...", "total_saved_prefix": "Kokku Säästetud:", "saved": "säästetud", "starting": "Käivitamine..."
    },
    "hr": {
        "app_name": "toWeb<span>P</span>.dev", "files": "datoteka", "total_saved_header": "Ukupno ušteđeno: ", "download_zip": "Preuzmi ZIP", "clear": "Očisti", "format": "Format", "quality": "Kvaliteta", "hero_title": "Besplatni skupni mrežni pretvarač slika u WebP", "hero_subtitle": "Skupna pretvorba na strani klijenta JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF u WEBP.<br/><strong>100% besplatno</strong>, <strong>trenutačno</strong> - iskorištavanje svih vaših jezgri, neograničeno u vašem pregledniku.<br/><span class='secondary-text'>Nema učitavanja - <strong>Vaše datoteke ostaju privatne</strong> i nije potrebna širina pojasa</span><br/><span class='secondary-text'>Nema kolačića - Nema praćenja!</span>", "drag_drop_images": "Povucite slike ovdje", "click_browse_p": "ili kliknite za pregled", "drag_drop": "Povuci i ispusti", "click_browse": "ili klikni", "feature_1_title": "🚀 Brzo i sigurno", "feature_1_desc": "Sve konverzije odvijaju se lokalno na vašem uređaju.", "feature_2_title": "📉 Pametna kompresija", "feature_2_desc": "Smanjite veličinu datoteke do 80% bez vidljivog gubitka kvalitete.", "feature_3_title": "⚡ Grupna obrada", "feature_3_desc": "Pretvorite stotine slika u sekundi.", "why_use_title": "Zašto koristiti ToWebP?", "why_use_p1": "ToWebP je pretvarač usmjeren na privatnost koji radi u potpunosti u vašem pregledniku.", "why_use_p2": "Bez kolačića, bez praćenja.", "download": "PREUZMI",
        "processing": "Obrada...", "parsing_files": "Analiza...", "waiting": "Čekanje...", "total_saved_prefix": "Ukupno Ušteđeno:", "saved": "ušteđeno", "starting": "Pokretanje..."
    },
    "is": {
        "app_name": "toWeb<span>P</span>.dev", "files": "skrár", "total_saved_header": "Heildar sparnaður: ", "download_zip": "Sækja ZIP", "clear": "Hreinsa", "format": "Snið", "quality": "Gæði", "hero_title": "Ókeypis hópupptaka mynda í WebP converter á netinu", "hero_subtitle": "Hópupptaka á hlið notanda JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF í WEBP.<br/><strong>100% ókeypis</strong>, <strong>samstundis</strong> - nýtir alla kjarna þína, ótakmarkað í vafranum þínum.<br/><span class='secondary-text'>Engin upphleðsla - <strong>Skrárnar þínar eru áfram einkamál</strong> og engin bandbreidd þörf</span><br/><span class='secondary-text'>Engar vafrakökur - Engin mæling!</span>", "drag_drop_images": "Dragðu myndir hingað", "click_browse_p": "eða smelltu til að velja", "drag_drop": "Dragðu og slepptu", "click_browse": "eða smelltu", "feature_1_title": "🚀 Hratt og öruggt", "feature_1_desc": "Allar breytingar fara fram staðbundið í tækinu þínu.", "feature_2_title": "📉 Snjöll þjöppun", "feature_2_desc": "Minnka skráarstærð um allt að 80% án sjáanlegs gæðataps.", "feature_3_title": "⚡ Lotuvinnsla", "feature_3_desc": "Breyttu hundruðum mynda á nokkrum sekúndum.", "why_use_title": "Af hverju að nota ToWebP?", "why_use_p1": "ToWebP er persónuverndarvænn breytir sem keyrir alveg í vafranum þínum.", "why_use_p2": "Engar kökur, engin mæling.", "download": "SÆKJA",
        "processing": "Vinnsla...", "parsing_files": "Greining...", "waiting": "Bíður...", "total_saved_prefix": "Heildar Sparnaður:", "saved": "sparað", "starting": "Ræsi..."
    },
    "lt": {
        "app_name": "toWeb<span>P</span>.dev", "files": "failų", "total_saved_header": "Iš viso sutaupyta: ", "download_zip": "Atsisiųsti ZIP", "clear": "Išvalyti", "format": "Formatas", "quality": "Kokybė", "hero_title": "Nemokamas masinis internetinis vaizdų konvertavimas į WebP", "hero_subtitle": "Kliento pusės partijos konvertavimas iš JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF į WEBP.<br/><strong>100% nemokama</strong>, <strong>iškart</strong> - išnaudojant visus jūsų branduolius, neribotai naršyklėje.<br/><span class='secondary-text'>Jokių įkėlimų - <strong>Jūsų failai lieka privatūs</strong> ir nereikia pralaidumo</span><br/><span class='secondary-text'>Jokių slapukų - Jokio sekimo!</span>", "drag_drop_images": "Vilkite vaizdus čia", "click_browse_p": "arba spustelėkite naršyti", "drag_drop": "Vilkti ir paleisti", "click_browse": "arba spustelėti", "feature_1_title": "🚀 Greita ir saugu", "feature_1_desc": "Visi konvertavimai vyksta vietoje jūsų įrenginyje.", "feature_2_title": "📉 Išmanus suspaudimas", "feature_2_desc": "Sumažinkite failo dydį iki 80% be matomo kokybės praradimo.", "feature_3_title": "⚡ Masinis apdorojimas", "feature_3_desc": "Konvertuokite šimtus vaizdų per kelias sekundes.", "why_use_title": "Kodėl naudoti ToWebP?", "why_use_p1": "ToWebP yra į privatumą orientuotas keitiklis, veikiantis tik jūsų naršyklėje.", "why_use_p2": "Jokių slapukų, jokio sekimo.", "download": "ATSISIŲSTI",
        "processing": "Apdorojama...", "parsing_files": "Analizuojama...", "waiting": "Laukiama...", "total_saved_prefix": "Iš Viso Sutaupyta:", "saved": "sutaupyta", "starting": "Paleidžiama..."
    },
    "lv": {
        "app_name": "toWeb<span>P</span>.dev", "files": "faili", "total_saved_header": "Kopā ietaupīts: ", "download_zip": "Lejupielādēt ZIP", "clear": "Notīrīt", "format": "Formāts", "quality": "Kvalitāte", "hero_title": "Bezmaksas masveida attēlu pārveidotājs uz WebP tiešsaistē", "hero_subtitle": "Klienta puses partijas konvertēšana no JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF uz WEBP.<br/><strong>100% bezmaksas</strong>, <strong>tūlītēja</strong> - izmantojot visus jūsu kodolus, neierobežoti jūsu pārlūkprogrammā.<br/><span class='secondary-text'>Nav augšupielādes - <strong>Jūsu faili paliek privāti</strong> un nav nepieciešams joslas platums</span><br/><span class='secondary-text'>Nav sīkfailu - Nav izsekošanas!</span>", "drag_drop_images": "Velciet attēlus šeit", "click_browse_p": "vai noklikšķiniet, lai pārlūkotu", "drag_drop": "Vilkt un nomest", "click_browse": "vai noklikšķināt", "feature_1_title": "🚀 Ātri un droši", "feature_1_desc": "Visi pārveidojumi notiek lokāli jūsu ierīcē.", "feature_2_title": "📉 Gudra saspiešana", "feature_2_desc": "Samaziniet faila lielumu līdz 80% bez redzama kvalitātes zuduma.", "feature_3_title": "⚡ Pakešu apstrāde", "feature_3_desc": "Konvertējiet simtiem attēlu sekundēs.", "why_use_title": "Kāpēc izmantot ToWebP?", "why_use_p1": "ToWebP ir privātuma orientēts pārveidotājs, kas darbojas pilnībā jūsu pārlūkprogrammā.", "why_use_p2": "Bez sīkfailiem, bez izsekošanas.", "download": "LEJUPIELĀDĒT",
        "processing": "Apstrāde...", "parsing_files": "Analīze...", "waiting": "Gaida...", "total_saved_prefix": "Kopā Ietaupīts:", "saved": "ietaupīts", "starting": "Sāk..."
    },
    "no": {
        "app_name": "toWeb<span>P</span>.dev", "files": "filer", "total_saved_header": "Totalt spart: ", "download_zip": "Last ned ZIP", "clear": "Tøm", "format": "Format", "quality": "Kvalitet", "hero_title": "Gratis online massekovertering av bilder til WebP", "hero_subtitle": "Klient-side batch-konvertering JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF til WEBP.<br/><strong>100% gratis</strong>, <strong>øyeblikkelig</strong> - utnytter alle kjernene dine, ubegrenset i nettleseren din.<br/><span class='secondary-text'>Ingen opplasting - <strong>Filene dine forblir private</strong> og ingen båndbredde kreves</span><br/><span class='secondary-text'>Ingen informasjonskapsler - Ingen sporing!</span>", "drag_drop_images": "Dra bilder hit", "click_browse_p": "eller klikk for å bla gjennom", "drag_drop": "Dra og slipp", "click_browse": "eller klikk", "feature_1_title": "🚀 Rask og sikker", "feature_1_desc": "Alle konverteringer skjer lokalt på enheten din.", "feature_2_title": "📉 Smart komprimering", "feature_2_desc": "Reduser filstørrelsen med opptil 80% uten synlig kvalitetstap.", "feature_3_title": "⚡ Batchbehandling", "feature_3_desc": "Konverter hundrevis av bilder på sekunder.", "why_use_title": "Hvorfor bruke ToWebP?", "why_use_p1": "ToWebP er en personvernfokusert konverterer som kjører helt i nettleseren din.", "why_use_p2": "Ingen informasjonskapsler, ingen sporing.", "download": "LAST NED",
        "processing": "Behandler...", "parsing_files": "Analyserer...", "waiting": "Venter...", "total_saved_prefix": "Totalt Spart:", "saved": "spart", "starting": "Starter..."
    },
    "sk": {
        "app_name": "toWeb<span>P</span>.dev", "files": "súborov", "total_saved_header": "Celkovo ušetrené: ", "download_zip": "Stiahnuť ZIP", "clear": "Vymazat", "format": "Formát", "quality": "Kvalita", "hero_title": "Bezplatný hromadný online prevodník obrázkov do WebP", "hero_subtitle": "Dávková konverzia na strane klienta JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF do WEBP.<br/><strong>100% zadarmo</strong>, <strong>okamžite</strong> - využitie všetkých vašich jadier, neobmedzene v prehliadači.<br/><span class='secondary-text'>Žiadne nahrávanie - <strong>Vaše súbory zostávajú súkromné</strong> a bez nárokov na šírku pásma</span><br/><span class='secondary-text'>Žiadne cookies - Žiadne sledovanie!</span>", "drag_drop_images": "Presuňte sem obrázky", "click_browse_p": "alebo kliknite pre prehľadávanie", "drag_drop": "Presunúť a pustiť", "click_browse": "alebo klikni", "feature_1_title": "🚀 Rýchle a bezpečné", "feature_1_desc": "Všetky prevody prebiehajú lokálne na vašom zariadení.", "feature_2_title": "📉 Inteligentná kompresia", "feature_2_desc": "Zmenšite veľkosť súboru až o 80 % bez viditeľnej straty kvality.", "feature_3_title": "⚡ Hromadné spracovanie", "feature_3_desc": "Preveďte stovky obrázkov v priebehu sekúnd.", "why_use_title": "Prečo používať ToWebP?", "why_use_p1": "ToWebP je konvertor zameraný na súkromie bežiaci vo vašom prehliadači.", "why_use_p2": "Žiadne cookies, žiadne sledovanie.", "download": "STIAHNUŤ",
        "processing": "Spracovanie...", "parsing_files": "Načítanie...", "waiting": "Čakanie...", "total_saved_prefix": "Celkovo Ušetrené:", "saved": "ušetrené", "starting": "Spúšťanie..."
    },
    "sl": {
        "app_name": "toWeb<span>P</span>.dev", "files": "datoteke", "total_saved_header": "Skupaj prihranjeno: ", "download_zip": "Prenesi ZIP", "clear": "Počisti", "format": "Format", "quality": "Kakovost", "hero_title": "Brezplačen spletni množični pretvornik slik v WebP", "hero_subtitle": "Množična pretvorba na strani odjemalca JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF v WEBP.<br/><strong>100-odstotno brezplačno</strong>, <strong>takojšnje</strong> - izkoriščanje vseh vaših jeder, neomejeno v brskalniku.<br/><span class='secondary-text'>Brez nalaganja - <strong>Vaše datoteke ostanejo zasebne</strong> in brez porabe pasovne širine</span><br/><span class='secondary-text'>Brez piškotkov - Brez sledenja!</span>", "drag_drop_images": "Povlecite slike sem", "click_browse_p": "ali kliknite za brskanje", "drag_drop": "Povleci in spusti", "click_browse": "ali klikni", "feature_1_title": "🚀 Hitro in varno", "feature_1_desc": "Vse pretvorbe potekajo lokalno na vaši napravi.", "feature_2_title": "📉 Pametno stiskanje", "feature_2_desc": "Zmanjšajte velikost datoteke do 80 % brez vidne izgube kakovosti.", "feature_3_title": "⚡ Paketna obdelava", "feature_3_desc": "Pretvori na stotine slik v nekaj sekundah.", "why_use_title": "Zakaj uporabljati ToWebP?", "why_use_p1": "ToWebP je pretvornik, osredotočen na zasebnost, ki deluje v celoti v vašem brskalniku.", "why_use_p2": "Brez piškotkov, brez sledenja.", "download": "PRENESI",
        "processing": "Obdelava...", "parsing_files": "Analiza...", "waiting": "Čakanje...", "total_saved_prefix": "Skupaj Prihranjeno:", "saved": "prihranjeno", "starting": "Zagon..."
    },
    "uk": {
        "app_name": "toWeb<span>P</span>.dev", "files": "файлів", "total_saved_header": "Всього збережено: ", "download_zip": "Завантажити ZIP", "clear": "Очистити", "format": "Формат", "quality": "Якість", "hero_title": "Безкоштовний масовий онлайн-конвертер зображень у WebP", "hero_subtitle": "Пакетна конвертація на стороні клієнта JPG, PNG, GIF, SVG, ICO, BMP, TIFF, HEIC, AVIF у WEBP.<br/><strong>100% безкоштовно</strong>, <strong>миттєво</strong> — з використанням усіх ваших ядер, без обмежень у браузері.<br/><span class='secondary-text'>Без завантажень — <strong>ваші файли залишаються приватними</strong> і без витрат трафіку</span><br/><span class='secondary-text'>Без файлів cookie — без відстеження!</span>", "drag_drop_images": "Перетягніть зображення сюди", "click_browse_p": "або натисніть для вибору", "drag_drop": "Перетягнути", "click_browse": "або клацніть", "feature_1_title": "🚀 Швидко та безпечно", "feature_1_desc": "Всі перетворення відбуваються локально на вашому пристрої.", "feature_2_title": "📉 Розумне стиснення", "feature_2_desc": "Зменшіть розмір до 80% без видимої втрати якості.", "feature_3_title": "⚡ Пакетна обробка", "feature_3_desc": "Конвертуйте сотні зображень за секунди.", "why_use_title": "Чому ToWebP?", "why_use_p1": "ToWebP працює повністю у вашому браузері.", "why_use_p2": "Без файлів cookie, без відстеження.", "download": "ЗАВАНТАЖИТИ",
        "processing": "Обробка...", "parsing_files": "Аналіз...", "waiting": "Очікування...", "total_saved_prefix": "Всього Збережено:", "saved": "збережено", "starting": "Запуск..."
    }
};

function getBrowserLanguage() {
    const lang = navigator.language || navigator.userLanguage;
    return lang.split('-')[0];
}

function applyTranslations(lang = "en") {
    const selectedLang = translations[lang] ? lang : "en";
    const t = translations[selectedLang];
    
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key]) {
            // Use innerHTML to support HTML tags in translations (e.g. app_name)
            el.innerHTML = t[key];
        }
    });
    document.documentElement.lang = selectedLang;
}

window.i18n = {
    t: (key, lang = getBrowserLanguage()) => {
        const selectedLang = translations[lang] ? lang : "en";
        return translations[selectedLang][key] || translations["en"][key] || key;
    },
    apply: applyTranslations,
    getLang: getBrowserLanguage
};
